#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Colorvia's String Catalog from reviewed in-repository translations."""

import json
from pathlib import Path


LANGUAGES = ["en", "ja", "es", "fr", "de", "it", "pt-BR", "ko", "zh-Hans", "zh-Hant", "ru"]


def bilingual(english, japanese):
    """Use reviewed Japanese copy and an English fallback for other locales."""
    return [english, japanese] + [english] * (len(LANGUAGES) - 2)


# Values are ordered according to LANGUAGES.
STRINGS = {
    "common.cancel": ["Cancel", "キャンセル", "Cancelar", "Annuler", "Abbrechen", "Annulla", "Cancelar", "취소", "取消", "取消", "Отмена"],
    "common.close": ["Close", "閉じる", "Cerrar", "Fermer", "Schließen", "Chiudi", "Fechar", "닫기", "关闭", "關閉", "Закрыть"],
    "common.delete": ["Delete", "削除", "Eliminar", "Supprimer", "Löschen", "Elimina", "Excluir", "삭제", "删除", "刪除", "Удалить"],
    "common.share": ["Share", "共有", "Compartir", "Partager", "Teilen", "Condividi", "Compartilhar", "공유", "分享", "分享", "Поделиться"],
    "contact.category": ["Type of enquiry", "お問い合わせの種類", "Tipo de consulta", "Type de demande", "Art der Anfrage", "Tipo di richiesta", "Tipo de solicitação", "문의 유형", "咨询类型", "諮詢類型", "Тип обращения"],
    "contact.category.bug": ["Bug report", "不具合", "Error", "Bug", "Fehler", "Problema", "Erro", "오류", "问题反馈", "問題回報", "Ошибка"],
    "contact.category.feature": ["Feature request", "機能の要望", "Sugerencia", "Suggestion", "Funktionswunsch", "Suggerimento", "Sugestão", "기능 제안", "功能建议", "功能建議", "Пожелание"],
    "contact.category.other": ["Other", "その他", "Otro", "Autre", "Sonstiges", "Altro", "Outro", "기타", "其他", "其他", "Другое"],
    "contact.category.question": ["Question", "質問", "Pregunta", "Question", "Frage", "Domanda", "Dúvida", "질문", "咨询", "諮詢", "Вопрос"],
    "contact.email_hint": ["Enter your email address", "メールアドレスを入力", "Introduce tu correo electrónico", "Saisissez votre adresse e-mail", "E-Mail-Adresse eingeben", "Inserisci il tuo indirizzo e-mail", "Digite seu e-mail", "이메일 주소 입력", "输入电子邮件地址", "輸入電子郵件地址", "Введите адрес эл. почты"],
    "contact.email_placeholder": ["Reply email address", "返信先メールアドレス", "Correo electrónico de respuesta", "Adresse e-mail de réponse", "E-Mail-Adresse für Antworten", "Indirizzo email per la risposta", "E-mail para resposta", "답변받을 이메일 주소", "回复电子邮件地址", "回覆電子郵件地址", "Адрес электронной почты для ответа"],
    "contact.error_title": ["Could not send", "送信できませんでした", "No se pudo enviar", "Échec de l’envoi", "Senden fehlgeschlagen", "Invio non riuscito", "Não foi possível enviar", "보내지 못했습니다", "发送失败", "傳送失敗", "Не удалось отправить"],
    "contact.footer": ["To reply and investigate issues, we send what you enter here along with your app version, OS, and locale. Your visit records are never sent.", "お問い合わせへの回答と不具合の調査のため、入力内容と、アプリのバージョンやOSなど利用環境に関する情報を送信します。訪問記録は送信しません。", "Para responder e investigar incidencias, enviamos lo que escribas junto con la versión de la app, el sistema operativo y el idioma. Tus registros de viaje nunca se envían.", "Pour répondre et enquêter, nous envoyons ce que vous saisissez ainsi que la version de l’app, le système et la langue. Vos données de voyage ne sont jamais envoyées.", "Um zu antworten und Fehler zu untersuchen, senden wir Ihre Eingaben zusammen mit App-Version, Betriebssystem und Sprache. Ihre Reisedaten werden nie gesendet.", "Per rispondere e analizzare i problemi inviamo quanto scrivi insieme a versione dell’app, sistema operativo e lingua. I tuoi dati di viaggio non vengono mai inviati.", "Para responder e investigar problemas, enviamos o que você escreve junto com a versão do app, o sistema e o idioma. Seus registros de viagem nunca são enviados.", "답변과 문제 확인을 위해 입력하신 내용과 앱 버전, OS, 언어 정보를 전송합니다. 방문 기록은 전송되지 않습니다.", "为了回复并排查问题，我们会发送您填写的内容以及应用版本、系统和语言信息。您的访问记录不会被发送。", "為了回覆並排查問題，我們會傳送您填寫的內容以及應用程式版本、系統和語言資訊。您的造訪紀錄不會被傳送。", "Чтобы ответить и разобраться в проблеме, мы отправляем введённые данные вместе с версией приложения, ОС и языком. Ваши записи о поездках не отправляются."],
    "contact.form_title": ["Send us a message", "メッセージを送る", "Envíanos un mensaje", "Envoyez-nous un message", "Nachricht senden", "Inviaci un messaggio", "Envie uma mensagem", "메시지 보내기", "发送消息", "傳送訊息", "Отправить сообщение"],
    "contact.lead": ["Send us a bug report, a question, or feedback. We read every message and usually reply within three business days.", "不具合、ご質問、ご意見をお送りください。内容を確認のうえ、通常3営業日以内を目安にご返信します。", "Envíanos un error, una pregunta o un comentario. Leemos todos los mensajes y solemos responder en un plazo de tres días hábiles.", "Envoyez-nous un bug, une question ou un commentaire. Nous lisons chaque message et répondons généralement sous trois jours ouvrés.", "Senden Sie uns einen Fehlerbericht, eine Frage oder Feedback. Wir lesen jede Nachricht und antworten in der Regel innerhalb von drei Werktagen.", "Inviaci una segnalazione, una domanda o un commento. Leggiamo ogni messaggio e di solito rispondiamo entro tre giorni lavorativi.", "Envie um erro, uma dúvida ou um comentário. Lemos todas as mensagens e normalmente respondemos em até três dias úteis.", "오류, 질문, 의견을 보내주세요. 모든 메시지를 확인하며 보통 3영업일 이내에 답변드립니다.", "欢迎反馈问题、提出疑问或分享意见。我们会查看每条消息，通常在三个工作日内回复。", "歡迎回報問題、提出疑問或分享意見。我們會查看每則訊息，通常在三個工作日內回覆。", "Сообщите об ошибке, задайте вопрос или поделитесь мнением. Мы читаем каждое сообщение и обычно отвечаем в течение трёх рабочих дней."],
    "contact.message": ["Message", "お問い合わせ内容", "Mensaje", "Message", "Nachricht", "Messaggio", "Mensagem", "문의 내용", "咨询内容", "諮詢內容", "Сообщение"],
    "contact.message_placeholder": ["Tell us what happened", "詳しい内容をご入力ください", "Cuéntanos qué ha pasado", "Décrivez ce qui s’est passé", "Bitte beschreiben Sie Ihr Anliegen", "Raccontaci cosa è successo", "Conte o que aconteceu", "자세한 내용을 입력해 주세요", "请输入详细内容", "請輸入詳細內容", "Опишите, что произошло"],
    "contact.name": ["Name", "お名前", "Nombre", "Nom", "Name", "Nome", "Nome", "이름", "姓名", "姓名", "Имя"],
    "contact.name_placeholder": ["Your name", "お名前", "Tu nombre", "Votre nom", "Ihr Name", "Il tuo nome", "Seu nome", "이름", "您的姓名", "您的姓名", "Ваше имя"],
    "contact.new_request": ["Write another message", "新しいお問い合わせを書く", "Escribir otro mensaje", "Écrire un autre message", "Weitere Nachricht schreiben", "Scrivi un altro messaggio", "Escrever outra mensagem", "새 문의 작성", "再写一条咨询", "再寫一則諮詢", "Написать ещё одно сообщение"],
    "contact.optional": ["Optional", "任意", "Opcional", "Facultatif", "Optional", "Facoltativo", "Opcional", "선택", "选填", "選填", "Необязательно"],
    "contact.privacy_note": ["Please review our Privacy Policy before sending.", "送信前にプライバシーポリシーをご確認ください。", "Consulta nuestra Política de privacidad antes de enviar.", "Consultez notre politique de confidentialité avant l’envoi.", "Bitte lesen Sie vor dem Senden unsere Datenschutzerklärung.", "Leggi la nostra Informativa sulla privacy prima di inviare.", "Leia nossa Política de Privacidade antes de enviar.", "보내기 전에 개인정보 처리방침을 확인해 주세요.", "发送前请查看隐私政策。", "傳送前請查看隱私權政策。", "Перед отправкой ознакомьтесь с политикой конфиденциальности."],
    "contact.receipt": ["Reference ID", "受付ID", "ID de referencia", "Numéro de suivi", "Vorgangsnummer", "ID di riferimento", "ID de referência", "접수 번호", "受理编号", "受理編號", "Номер обращения"],
    "contact.reply_note": ["You can send this without turning it on. We only ask for an email address if you want a reply.", "オフのままでも送信できます。返信をご希望の場合のみ、メールアドレスをお伺いします。", "Puedes enviarlo sin activarlo. Solo pedimos un correo electrónico si quieres respuesta.", "Vous pouvez envoyer sans l’activer. Nous ne demandons une adresse e-mail que si vous souhaitez une réponse.", "Sie können auch ohne diese Option senden. Wir fragen nur nach einer E-Mail-Adresse, wenn Sie eine Antwort möchten.", "Puoi inviare anche senza attivarlo. Chiediamo un indirizzo e-mail solo se desideri una risposta.", "Você pode enviar sem ativar. Só pedimos um e-mail se você quiser resposta.", "켜지 않아도 보낼 수 있습니다. 답변을 원하실 때만 이메일 주소를 여쭤봅니다.", "不开启也可以发送。仅在您希望收到回复时才需要填写电子邮件地址。", "不開啟也可以傳送。僅在您希望收到回覆時才需要填寫電子郵件地址。", "Можно отправить и без этого. Адрес эл. почты нужен, только если вы ждёте ответ."],
    "contact.reply_requested": ["I’d like a reply", "返信を希望する", "Quiero recibir respuesta", "Je souhaite une réponse", "Ich möchte eine Antwort", "Vorrei una risposta", "Quero receber resposta", "답변을 받고 싶습니다", "希望收到回复", "希望收到回覆", "Хочу получить ответ"],
    "contact.reply_required_note": ["A question needs an answer, so we ask for an email address.", "ご質問には返信が必要なため、メールアドレスをお伺いします。", "Una pregunta necesita respuesta, por eso pedimos un correo electrónico.", "Une question appelle une réponse : nous vous demandons donc une adresse e-mail.", "Eine Frage braucht eine Antwort – dafür benötigen wir Ihre E-Mail-Adresse.", "Una domanda richiede una risposta, perciò chiediamo un indirizzo e-mail.", "Uma dúvida precisa de resposta, por isso pedimos um e-mail.", "질문에는 답변이 필요하므로 이메일 주소를 여쭤봅니다.", "咨询需要回复，因此需要填写电子邮件地址。", "諮詢需要回覆，因此需要填寫電子郵件地址。", "На вопрос нужен ответ, поэтому мы просим адрес эл. почты."],
    "contact.required": ["Required", "必須", "Obligatorio", "Obligatoire", "Erforderlich", "Obbligatorio", "Obrigatório", "필수", "必填", "必填", "Обязательно"],
    "contact.send": ["Send", "送信", "Enviar", "Envoyer", "Senden", "Invia", "Enviar", "보내기", "发送", "傳送", "Отправить"],
    "contact.sent_body": ["We’ll review it and usually reply within three business days.", "内容を確認のうえ、通常3営業日以内を目安にご返信します。", "La revisaremos y normalmente responderemos en un plazo de tres días hábiles.", "Nous l’examinerons et répondrons généralement sous trois jours ouvrés.", "Wir prüfen sie und antworten in der Regel innerhalb von drei Werktagen.", "La esamineremo e di solito risponderemo entro tre giorni lavorativi.", "Vamos analisá-la e normalmente responder em até três dias úteis.", "내용을 확인한 뒤 보통 3영업일 이내에 답변드립니다.", "我们会查看内容，通常在三个工作日内回复。", "我們會查看內容，通常在三個工作日內回覆。", "Мы изучим его и обычно отвечаем в течение трёх рабочих дней."],
    "contact.sent_body_no_reply": ["We’ll read what you sent. You didn’t ask for a reply, so we won’t email you back.", "お送りいただいた内容を確認します。返信のご希望はいただいていないため、こちらからのご連絡はありません。", "Leeremos tu mensaje. Como no pediste respuesta, no te escribiremos.", "Nous lirons votre message. Comme vous n’avez pas demandé de réponse, nous ne vous recontacterons pas.", "Wir lesen Ihre Nachricht. Da Sie keine Antwort gewünscht haben, melden wir uns nicht zurück.", "Leggeremo il tuo messaggio. Poiché non hai chiesto una risposta, non ti ricontatteremo.", "Vamos ler sua mensagem. Como você não pediu resposta, não entraremos em contato.", "보내주신 내용을 확인하겠습니다. 답변을 요청하지 않으셨으므로 별도의 연락은 드리지 않습니다.", "我们会阅读您发送的内容。由于您未要求回复，我们不会另行联系。", "我們會閱讀您傳送的內容。由於您未要求回覆，我們不會另行聯繫。", "Мы прочитаем ваше сообщение. Ответ вы не запрашивали, поэтому писать вам не будем."],
    "contact.sent_title": ["We’ve received your message", "お問い合わせを受け付けました", "Hemos recibido tu mensaje", "Nous avons bien reçu votre message", "Ihre Nachricht ist eingegangen", "Abbiamo ricevuto il tuo messaggio", "Recebemos sua mensagem", "문의가 접수되었습니다", "已收到您的咨询", "已收到您的諮詢", "Мы получили ваше сообщение"],
    "contact.submitting": ["Sending…", "送信しています…", "Enviando…", "Envoi…", "Wird gesendet…", "Invio…", "Enviando…", "보내는 중…", "正在发送…", "正在傳送…", "Отправка…"],
    "contact.web_fallback": ["Open the support form on the web", "Webのサポートフォームを開く", "Abrir el formulario web de soporte", "Ouvrir le formulaire d’assistance en ligne", "Support-Formular im Web öffnen", "Apri il modulo di assistenza sul web", "Abrir o formulário de suporte na web", "웹 지원 양식 열기", "打开网页版支持表单", "開啟網頁版支援表單", "Открыть веб-форму поддержки"],
    "continent.africa": ["Africa", "アフリカ", "África", "Afrique", "Afrika", "Africa", "África", "아프리카", "非洲", "非洲", "Африка"],
    "continent.asia": ["Asia", "アジア", "Asia", "Asie", "Asien", "Asia", "Ásia", "아시아", "亚洲", "亞洲", "Азия"],
    "continent.europe": ["Europe", "ヨーロッパ", "Europa", "Europe", "Europa", "Europa", "Europa", "유럽", "欧洲", "歐洲", "Европа"],
    "continent.north_america": ["North America", "北アメリカ", "Norteamérica", "Amérique du Nord", "Nordamerika", "Nord America", "América do Norte", "북아메리카", "北美洲", "北美洲", "Северная Америка"],
    "continent.oceania": ["Oceania", "オセアニア", "Oceanía", "Océanie", "Ozeanien", "Oceania", "Oceania", "오세아니아", "大洋洲", "大洋洲", "Океания"],
    "continent.south_america": ["South America", "南アメリカ", "Sudamérica", "Amérique du Sud", "Südamerika", "Sud America", "América do Sul", "남아메리카", "南美洲", "南美洲", "Южная Америка"],
    "country_detail.code": bilingual("Country code", "国コード"),
    "country_detail.continent": bilingual("Continent", "大陸"),
    "country_detail.status": bilingual("Visit status", "訪問状態"),
    "country_list.remove_visited": bilingual("Remove from visited", "訪問済みから外す"),
    "country_list.title": bilingual("Choose countries", "国を選ぶ"),
    "faq.account.body": ["No. Colorvia works without creating an account.", "いいえ。Colorviaはアカウントを作成せずに利用できます。", "No. Colorvia funciona sin crear una cuenta.", "Non. Colorvia fonctionne sans créer de compte.", "Nein. Colorvia funktioniert ohne Konto.", "No. Colorvia funziona senza creare un account.", "Não. O Colorvia funciona sem criar uma conta.", "아니요. 계정을 만들지 않고 사용할 수 있습니다.", "不需要。Colorvia无需创建账户即可使用。", "不需要。Colorvia 無須建立帳號即可使用。", "Нет. Colorvia работает без учётной записи."],
    "faq.account.title": ["Do I need an account?", "アカウントは必要ですか？", "¿Necesito una cuenta?", "Ai-je besoin d’un compte ?", "Brauche ich ein Konto?", "Serve un account?", "Preciso de uma conta?", "계정이 필요한가요?", "需要账户吗？", "需要帳號嗎？", "Нужна ли учётная запись?"],
    "faq.percentage.body": ["The percentage is calculated against the 195 countries defined by Colorvia.", "Colorviaが定義する195か国を基準に計算しています。", "El porcentaje se calcula sobre los 195 países definidos por Colorvia.", "Le pourcentage est calculé sur les 195 pays définis par Colorvia.", "Der Prozentsatz basiert auf den 195 von Colorvia definierten Ländern.", "La percentuale è calcolata sui 195 paesi definiti da Colorvia.", "A porcentagem é calculada com base nos 195 países definidos pelo Colorvia.", "Colorvia가 정의한 195개국을 기준으로 계산합니다.", "百分比以Colorvia定义的195个国家为基准计算。", "百分比以 Colorvia 定義的 195 個國家為基準計算。", "Процент рассчитывается относительно 195 стран, определённых Colorvia."],
    "faq.percentage.title": ["How is the percentage calculated?", "世界割合はどう計算されますか？", "¿Cómo se calcula el porcentaje?", "Comment le pourcentage est-il calculé ?", "Wie wird der Prozentsatz berechnet?", "Come viene calcolata la percentuale?", "Como a porcentagem é calculada?", "세계 비율은 어떻게 계산하나요?", "世界比例如何计算？", "世界比例如何計算？", "Как рассчитывается процент?"],
    "faq.storage.body": ["Visit data is stored locally on your device.", "訪問データは端末内に保存されます。", "Los datos se guardan localmente en el dispositivo.", "Les visites sont stockées localement sur votre appareil.", "Besuchsdaten werden lokal auf dem Gerät gespeichert.", "I dati sono salvati localmente sul dispositivo.", "Os dados são armazenados localmente no dispositivo.", "방문 데이터는 기기에 저장됩니다.", "访问数据存储在你的设备上。", "造訪資料會儲存在你的裝置上。", "Данные хранятся локально на устройстве."],
    "faq.storage.title": ["Where is my data stored?", "データはどこに保存されますか？", "¿Dónde se guardan mis datos?", "Où mes données sont-elles stockées ?", "Wo werden meine Daten gespeichert?", "Dove vengono salvati i dati?", "Onde meus dados são armazenados?", "데이터는 어디에 저장되나요?", "数据存储在哪里？", "資料儲存在哪裡？", "Где хранятся данные?"],
    "filter.all": bilingual("All", "すべて"),
    "filter.title": bilingual("Filter", "フィルター"),
    "filter.unvisited": bilingual("Not visited", "未訪問"),
    "filter.visited": bilingual("Visited", "訪問済み"),
    "format.country_count": ["%d countries", "%dか国", "%d países", "%d pays", "%d Länder", "%d paesi", "%d países", "%d개국", "%d个国家", "%d 個國家", "%d стран"],
    "format.country_count_one": ["1 country", "1か国", "1 país", "1 pays", "1 Land", "1 paese", "1 país", "1개국", "1个国家", "1 個國家", "1 страна"],
    "format.france_department_fraction": bilingual("%d / 101 departments", "%d / 101 地域"),
    "format.france_row_unvisited": bilingual("Not visited · %d / 101 departments", "未訪問・%d / 101地域"),
    "format.france_row_visited": bilingual("Visited · %d / 101 departments", "訪問済み・%d / 101地域"),
    "format.france_share_message": bilingual("I have visited %d departments in France with Colorvia.", "Colorviaでフランスの%d地域を訪れました。"),
    "format.japan_explored": bilingual("Japan explored: %@%%", "日本の探索率：%@%%"),
    "format.japan_row_unvisited": bilingual("Not visited · %d / 47 prefectures", "未訪問・%d / 47都道府県"),
    "format.japan_row_visited": bilingual("Visited · %d / 47 prefectures", "訪問済み・%d / 47都道府県"),
    "format.japan_share_message": bilingual("I have visited %d prefectures in Japan with Colorvia.", "Colorviaで日本の%d都道府県を訪れました。"),
    "format.map_visited": ["%d countries visited", "%dか国を訪問済み", "%d países visitados", "%d pays visités", "%d Länder besucht", "%d paesi visitati", "%d países visitados", "%d개국 방문", "已访问%d个国家", "已造訪 %d 個國家", "Посещено стран: %d"],
    "format.number": bilingual("%d", "%d"),
    "format.percentage": bilingual("%@%%", "%@%%"),
    "format.place_match_reason": bilingual("Matches %@", "%@に一致"),
    "format.prefecture_fraction": bilingual("%d / 47", "%d / 47"),
    "format.remove_country_prompt": bilingual("Remove %@ from visited?", "%@を訪問済みから外しますか？"),
    "format.remove_france_message": bilingual("%d saved regions will also be removed.", "登録されている%d件の地域も訪問済みから外されます。"),
    "format.remove_japan_message": bilingual("%d saved prefectures will also be removed.", "登録されている%d件の都道府県も訪問済みから外されます。"),
    "format.remove_subdivision_message": bilingual("%d saved regions will also be removed.", "登録されている%d件の地域も訪問済みから外されます。"),
    "format.selected_count": ["Done (%d)", "完了（%d）", "Listo (%d)", "Terminé (%d)", "Fertig (%d)", "Fine (%d)", "Concluir (%d)", "완료 (%d)", "完成（%d）", "完成（%d）", "Готово (%d)"],
    "format.selected_department_count": bilingual("Done (%d)", "完了（%d）"),
    "format.selected_prefecture_count": bilingual("Done (%d)", "完了（%d）"),
    "format.selected_subdivision_count": bilingual("Done (%d)", "完了（%d）"),
    "format.share_message": ["I have visited %d countries with Colorvia.", "Colorviaで%dか国を訪れました。", "He visitado %d países con Colorvia.", "J’ai visité %d pays avec Colorvia.", "Ich habe mit Colorvia %d Länder besucht.", "Ho visitato %d paesi con Colorvia.", "Visitei %d países com o Colorvia.", "Colorvia로 %d개국을 방문했어요.", "我用Colorvia记录了%d个到访国家。", "我用 Colorvia 記錄了 %d 個造訪國家。", "Я посетил(а) %d стран с Colorvia."],
    "format.subdivision_row_unvisited": bilingual("Not visited · %d / %d regions", "未訪問・%d / %d地域"),
    "format.subdivision_row_visited": bilingual("Visited · %d / %d regions", "訪問済み・%d / %d地域"),
    "format.visited_country_summary": bilingual("%d countries visited", "%dか国を訪問済み"),
    "format.visited_department_summary": bilingual("%d departments visited", "%d地域"),
    "format.visited_prefecture_summary": bilingual("%d prefectures visited", "%d都道府県"),
    "france.flag": bilingual("🇫🇷", "🇫🇷"),
    "france_detail.department_progress": bilingual("Department progress", "地域の進捗"),
    "france_detail.open_map": bilingual("Open France map", "フランス地図を開く"),
    "france_detail.remove_all": bilingual("Remove France and all regions", "フランスと地域をすべて外す"),
    "france_detail.remove_prompt": bilingual("Remove France from visited?", "フランスを訪問済みから外しますか？"),
    "france_list.choose": bilingual("Choose regions", "地域を選ぶ"),
    "france_list.search": bilingual("Department, city, or code", "地域名・都市名・コード"),
    "france_list.title": bilingual("Choose regions", "フランスの地域を選ぶ"),
    "france_map.accessibility_label": bilingual("Map of France departments", "フランス地域地図"),
    "france_share.departments": bilingual("DEPARTMENTS", "地域"),
    "france_share.percentage_prefix": bilingual("France explored: ", "フランスの"),
    "france_share.poster_title": bilingual("MY FRANCE", "わたしのフランス地図"),
    "france_share.square": bilingual("Square poster", "正方形ポスター"),
    "france_share.story": bilingual("Story poster", "ストーリーポスター"),
    "france_share.title": bilingual("Share France map", "フランス地図を共有"),
    "france_stats.title": bilingual("Your France", "あなたのフランス"),
    "guide.add.body": ["Tap the plus button, search for a country, and mark it as visited.", "＋ボタンを押し、国を検索して訪問済みにします。", "Toca el botón más, busca un país y márcalo como visitado.", "Touchez le bouton plus, recherchez un pays et marquez-le comme visité.", "Tippe auf Plus, suche ein Land und markiere es als besucht.", "Tocca il pulsante più, cerca un paese e segnalo come visitato.", "Toque no botão de mais, procure um país e marque como visitado.", "＋ 버튼을 누르고 국가를 검색해 방문한 국가로 표시하세요.", "点击加号按钮，搜索国家并标记为已访问。", "點一下加號按鈕，搜尋國家並標記為已造訪。", "Нажмите плюс, найдите страну и отметьте её как посещённую."],
    "guide.add.title": ["Add a country", "国を追加する", "Añadir un país", "Ajouter un pays", "Land hinzufügen", "Aggiungi un paese", "Adicionar um país", "국가 추가", "添加国家", "新增國家", "Добавление страны"],
    "guide.map.body": ["Pinch to zoom, drag to move, or use the map controls to reset the view.", "ピンチで拡大し、ドラッグで移動できます。操作ボタンから初期表示へ戻せます。", "Pellizca para ampliar, arrastra para mover o usa los controles para restablecer.", "Pincez pour zoomer, faites glisser pour déplacer ou utilisez les commandes.", "Zoome mit zwei Fingern, verschiebe die Karte oder setze sie über die Steuerung zurück.", "Pizzica per ingrandire, trascina per spostare o usa i comandi.", "Use o gesto de pinça para ampliar, arraste para mover ou use os controles.", "손가락으로 확대하고 드래그해 이동하거나 지도 버튼으로 초기화하세요.", "双指缩放、拖动地图，或使用地图控件重置视图。", "雙指縮放、拖曳地圖，或使用地圖控制項目重設顯示。", "Масштабируйте жестом, перемещайте карту или используйте кнопки сброса."],
    "guide.map.title": ["Explore the map", "地図を操作する", "Explorar el mapa", "Explorer la carte", "Karte erkunden", "Esplora la mappa", "Explorar o mapa", "지도 둘러보기", "浏览地图", "瀏覽地圖", "Работа с картой"],
    "guide.start.body": ["Colorvia colors the countries you have visited and keeps a simple record of your world.", "Colorviaは訪れた国を色づけ、自分の世界をシンプルに記録します。", "Colorvia colorea los países que has visitado y registra tu mundo.", "Colorvia colore les pays visités et conserve une trace simple de votre monde.", "Colorvia färbt besuchte Länder und hält deine Welt einfach fest.", "Colorvia colora i paesi visitati e registra il tuo mondo.", "O Colorvia colore os países visitados e registra o seu mundo.", "Colorvia는 방문한 국가를 색칠해 나의 세계를 기록합니다.", "Colorvia为你去过的国家上色，简单记录你的世界。", "Colorvia 為你去過的國家上色，簡單記錄你的世界。", "Colorvia раскрашивает посещённые страны и сохраняет вашу карту мира."],
    "guide.start.title": ["Getting started", "はじめに", "Primeros pasos", "Bien démarrer", "Erste Schritte", "Per iniziare", "Primeiros passos", "시작하기", "开始使用", "開始使用", "Начало работы"],
    "home.add_country": ["Add a visited country", "訪れた国を追加", "Añadir un país visitado", "Ajouter un pays visité", "Besuchtes Land hinzufügen", "Aggiungi un paese visitato", "Adicionar país visitado", "방문한 국가 추가", "添加到访国家", "新增造訪國家", "Добавить посещённую страну"],
    "japan.flag": bilingual("🇯🇵", "🇯🇵"),
    "japan_detail.mark_visited": bilingual("Mark as visited", "訪問済みにする"),
    "japan_detail.open_map": bilingual("Open prefecture map", "都道府県マップを開く"),
    "japan_detail.prefecture_progress": bilingual("Prefecture progress", "都道府県の進捗"),
    "japan_detail.remove_all": bilingual("Remove Japan and all prefectures", "日本と都道府県をすべて外す"),
    "japan_detail.remove_prompt": bilingual("Remove Japan from visited?", "日本を訪問済みから外しますか？"),
    "japan_map.accessibility_label": bilingual("Map of Japan", "日本地図"),
    "japan_stats.by_region": bilingual("By region", "地方別"),
    "japan_stats.no_prefectures": bilingual("No prefectures visited yet", "訪れた都道府県はまだありません"),
    "japan_stats.swipe_up": bilingual("Swipe up to see statistics", "上にスワイプして統計を表示"),
    "japan_stats.title": bilingual("Your Japan", "あなたの日本"),
    "japan_stats.visited_prefectures": bilingual("Visited prefectures", "訪れた都道府県"),
    "map.accessibility_label": ["World map", "世界地図", "Mapa mundial", "Carte du monde", "Weltkarte", "Mappa del mondo", "Mapa-múndi", "세계 지도", "世界地图", "世界地圖", "Карта мира"],
    "map.reset": ["Reset map", "地図をリセット", "Restablecer mapa", "Réinitialiser la carte", "Karte zurücksetzen", "Reimposta mappa", "Redefinir mapa", "지도 초기화", "重置地图", "重設地圖", "Сбросить карту"],
    "map.zoom_in": ["Zoom in", "拡大", "Acercar", "Zoom avant", "Vergrößern", "Ingrandisci", "Ampliar", "확대", "放大", "放大", "Приблизить"],
    "map.zoom_out": ["Zoom out", "縮小", "Alejar", "Zoom arrière", "Verkleinern", "Riduci", "Reduzir", "축소", "缩小", "縮小", "Отдалить"],
    "onboarding.choose_countries": ["Choose countries", "国を選ぶ", "Elegir países", "Choisir des pays", "Länder auswählen", "Scegli i paesi", "Escolher países", "국가 선택", "选择国家", "選擇國家", "Выбрать страны"],
    "onboarding.subtitle": ["Just choose the countries you have visited.", "行ったことのある国を選ぶだけ。", "Solo elige los países que has visitado.", "Choisissez simplement les pays visités.", "Wähle einfach die Länder aus, die du besucht hast.", "Scegli i paesi che hai visitato.", "Basta escolher os países que você visitou.", "가 본 국가를 선택하기만 하면 돼요.", "只需选择你去过的国家。", "只要選擇你去過的國家。", "Просто выберите страны, в которых вы побывали."],
    "onboarding.title": ["Color the world you have seen.", "訪れた世界を、色にしよう。", "Dale color al mundo que has visto.", "Mettez en couleur le monde que vous avez vu.", "Färbe die Welt, die du gesehen hast.", "Colora il mondo che hai visto.", "Dê cor ao mundo que você conheceu.", "내가 본 세계를 색칠해 보세요.", "为你看过的世界上色。", "為你看過的世界上色。", "Раскрасьте мир, который вы увидели."],
    "picker.search": ["Country name or code", "国名・国コード", "Nombre o código del país", "Nom ou code du pays", "Ländername oder Code", "Nome o codice del paese", "Nome ou código do país", "국가명 또는 국가 코드", "国家名称或代码", "國家名稱或代碼", "Название или код страны"],
    "picker.title": ["Choose visited countries", "訪れた国を選ぶ", "Elige los países visitados", "Choisir les pays visités", "Besuchte Länder auswählen", "Scegli i paesi visitati", "Escolha os países visitados", "방문한 국가 선택", "选择到访国家", "選擇造訪國家", "Выберите посещённые страны"],
    "prefecture_list.choose": bilingual("Choose prefectures", "都道府県を選ぶ"),
    "prefecture_list.search": bilingual("Prefecture name or code", "都道府県名・コード"),
    "prefecture_list.title": bilingual("Choose prefectures", "都道府県を選ぶ"),
    "region.chubu": bilingual("Chubu", "中部"),
    "region.chugoku": bilingual("Chugoku", "中国"),
    "region.hokkaido": bilingual("Hokkaido", "北海道"),
    "region.kanto": bilingual("Kanto", "関東"),
    "region.kinki": bilingual("Kinki", "近畿"),
    "region.kyushu_okinawa": bilingual("Kyushu & Okinawa", "九州・沖縄"),
    "region.shikoku": bilingual("Shikoku", "四国"),
    "region.tohoku": bilingual("Tohoku", "東北"),
    "settings.about": ["About", "アプリについて", "Acerca de", "À propos", "Über die App", "Informazioni", "Sobre", "앱 정보", "关于", "關於", "О приложении"],
    "settings.admob_license_description": bilingual(
        "Banner ads and consent messaging use Google Mobile Ads SDK and the User Messaging Platform.",
        "バナー広告と同意メッセージには、Google Mobile Ads SDKおよびUser Messaging Platformを使用しています。",
    ),
    "settings.admob_license_title": bilingual("Google Mobile Ads SDK", "Google Mobile Ads SDK"),
    "settings.app_details": ["App details", "アプリ詳細", "Detalles de la app", "Détails de l’app", "App-Details", "Dettagli app", "Detalhes do app", "앱 상세 정보", "应用详情", "App 詳細資料", "Сведения о приложении"],
    "settings.app_studio": ["App studio", "アプリスタジオ", "Estudio de apps", "Studio d’apps", "App-Studio", "Studio app", "Estúdio de apps", "앱 스튜디오", "应用工作室", "App 工作室", "Студия приложений"],
    "settings.appearance": ["Appearance", "外観", "Apariencia", "Apparence", "Erscheinungsbild", "Aspetto", "Aparência", "화면 모드", "外观", "外觀", "Оформление"],
    "settings.appearance.dark": ["Dark", "ダーク", "Oscuro", "Sombre", "Dunkel", "Scuro", "Escuro", "다크", "深色", "深色", "Тёмное"],
    "settings.appearance.light": ["Light", "ライト", "Claro", "Clair", "Hell", "Chiaro", "Claro", "라이트", "浅色", "淺色", "Светлое"],
    "settings.appearance.system": ["System", "システム", "Sistema", "Système", "System", "Sistema", "Sistema", "시스템", "跟随系统", "跟隨系統", "Системное"],
    "settings.contact": ["Contact us", "お問合せ", "Contacto", "Nous contacter", "Kontakt", "Contatti", "Fale conosco", "문의하기", "联系我们", "聯絡我們", "Связаться с нами"],
    "settings.copyright": ["Copyright", "コピーライト", "Copyright", "Copyright", "Copyright", "Copyright", "Copyright", "저작권", "版权", "著作權", "Авторские права"],
    "settings.data": ["Data", "データ", "Datos", "Données", "Daten", "Dati", "Dados", "데이터", "数据", "資料", "Данные"],
    "settings.data_management": ["Data management", "データ管理", "Gestión de datos", "Gestion des données", "Datenverwaltung", "Gestione dati", "Gerenciamento de dados", "데이터 관리", "数据管理", "資料管理", "Управление данными"],
    "settings.data_management_footer": ["Deleting visit data cannot be undone.", "訪問データを削除すると元に戻せません。", "Los datos eliminados no se pueden recuperar.", "Les visites supprimées ne peuvent pas être restaurées.", "Gelöschte Besuchsdaten können nicht wiederhergestellt werden.", "I dati eliminati non possono essere ripristinati.", "Os dados excluídos não podem ser recuperados.", "삭제한 방문 데이터는 복구할 수 없습니다.", "删除的访问数据无法恢复。", "刪除的造訪資料無法復原。", "Удалённые данные нельзя восстановить."],
    "settings.developer": ["Developer", "開発", "Desarrollador", "Développeur", "Entwickler", "Sviluppatore", "Desenvolvedor", "개발", "开发者", "開發者", "Разработчик"],
    "settings.developer_site": ["Developer website", "開発者サイト", "Sitio del desarrollador", "Site du développeur", "Entwickler-Website", "Sito dello sviluppatore", "Site do desenvolvedor", "개발자 사이트", "开发者网站", "開發者網站", "Сайт разработчика"],
    "settings.display": ["Display", "表示", "Pantalla", "Affichage", "Anzeige", "Schermo", "Exibição", "디스플레이", "显示", "顯示", "Экран"],
    "settings.email": ["Email address", "メールアドレス", "Correo electrónico", "Adresse e-mail", "E-Mail-Adresse", "Indirizzo email", "Endereço de e-mail", "이메일 주소", "电子邮件地址", "電子郵件地址", "Адрес электронной почты"],
    "settings.export_json": bilingual("Export JSON", "JSONを書き出す"),
    "settings.faq": ["Frequently asked questions", "よくある質問", "Preguntas frecuentes", "Questions fréquentes", "Häufige Fragen", "Domande frequenti", "Perguntas frequentes", "자주 묻는 질문", "常见问题", "常見問題", "Частые вопросы"],
    "settings.geonames_description": bilingual("Offline city and alternate-name search for the additional regional maps uses GeoNames data under CC BY 4.0.", "追加した地域マップのオフライン都市・別名検索には、CC BY 4.0のGeoNamesデータを使用しています。"),
    "settings.guide": ["User guide", "利用ガイド", "Guía de uso", "Guide d’utilisation", "Benutzerhandbuch", "Guida all’uso", "Guia de uso", "이용 가이드", "使用指南", "使用指南", "Руководство"],
    "settings.import_complete": bilingual("Import complete", "読み込みが完了しました"),
    "settings.import_json": bilingual("Import JSON", "JSONを読み込む"),
    "settings.import_parent_title": bilingual(
        "Regions have unvisited parent countries",
        "未訪問国の地域データがあります",
    ),
    "settings.import_repair_parents": bilingual(
        "Mark countries visited and import",
        "国を訪問済みに補正して読み込む",
    ),
    "settings.import_skip_regions": bilingual(
        "Skip those regions and import",
        "該当地域を除外して読み込む",
    ),
    "settings.information": ["Information", "情報", "Información", "Informations", "Informationen", "Informazioni", "Informações", "정보", "信息", "資訊", "Информация"],
    "settings.insee_description": bilingual("French department, region, and commune names and codes use Insee’s 2026 Code officiel géographique.", "フランスの地域圏・地域・コミューンの名称とコードには、InseeのCode officiel géographique 2026を使用しています。"),
    "settings.japan_address_description": bilingual("Japanese municipality search uses Geolonia’s address index, derived from Japanese government address data.", "日本の市区町村検索には、日本政府の住所データをもとにしたGeoloniaの住所インデックスを使用しています。"),
    "settings.json_footer": bilingual("Export a backup or replace this device’s visit data from a Colorvia JSON file.", "バックアップを書き出すか、ColorviaのJSONファイルからこの端末の訪問データを置き換えます。"),
    "settings.language": ["Language", "言語設定", "Idioma", "Langue", "Sprache", "Lingua", "Idioma", "언어", "语言", "語言", "Язык"],
    "settings.licenses": ["Open source licenses", "オープンソースライセンス", "Licencias de código abierto", "Licences open source", "Open-Source-Lizenzen", "Licenze open source", "Licenças de código aberto", "오픈 소스 라이선스", "开源许可证", "開放原始碼授權", "Лицензии открытого ПО"],
    "settings.map_color": ["Map color", "マップカラー管理", "Color del mapa", "Couleur de la carte", "Kartenfarbe", "Colore mappa", "Cor do mapa", "지도 색상", "地图颜色", "地圖顏色", "Цвет карты"],
    "settings.map_color.amber": ["Amber", "アンバー", "Ámbar", "Ambre", "Bernstein", "Ambra", "Âmbar", "앰버", "琥珀色", "琥珀色", "Янтарный"],
    "settings.map_color.coral": ["Coral", "コーラル", "Coral", "Corail", "Koralle", "Corallo", "Coral", "코랄", "珊瑚色", "珊瑚色", "Коралловый"],
    "settings.map_color.ocean": ["Ocean", "オーシャン", "Océano", "Océan", "Ozean", "Oceano", "Oceano", "오션", "海洋蓝", "海洋藍", "Океан"],
    "settings.map_color.teal": ["Teal", "ティール", "Verde azulado", "Sarcelle", "Petrol", "Verde acqua", "Verde-azulado", "청록", "青绿色", "藍綠色", "Бирюзовый"],
    "settings.natural_earth": ["Natural Earth data", "Natural Earth データ", "Datos de Natural Earth", "Données Natural Earth", "Natural-Earth-Daten", "Dati Natural Earth", "Dados do Natural Earth", "Natural Earth 데이터", "Natural Earth 数据", "Natural Earth 資料", "Данные Natural Earth"],
    "settings.natural_earth_description": ["Colorvia uses public-domain Natural Earth map data.", "ColorviaはパブリックドメインのNatural Earth地図データを使用しています。", "Colorvia utiliza datos cartográficos de dominio público de Natural Earth.", "Colorvia utilise les données cartographiques du domaine public Natural Earth.", "Colorvia verwendet gemeinfreie Kartendaten von Natural Earth.", "Colorvia utilizza dati cartografici Natural Earth di pubblico dominio.", "O Colorvia usa dados de mapa em domínio público do Natural Earth.", "Colorvia는 퍼블릭 도메인 Natural Earth 지도 데이터를 사용합니다.", "Colorvia使用公共领域的Natural Earth地图数据。", "Colorvia 使用公有領域的 Natural Earth 地圖資料。", "Colorvia использует общедоступные картографические данные Natural Earth."],
    "settings.official_site": ["Official website", "公式サイト", "Sitio oficial", "Site officiel", "Offizielle Website", "Sito ufficiale", "Site oficial", "공식 사이트", "官方网站", "官方網站", "Официальный сайт"],
    "settings.personalization": ["Personalization", "カスタマイズ", "Personalización", "Personnalisation", "Personalisierung", "Personalizzazione", "Personalização", "개인 설정", "个性化", "個人化", "Персонализация"],
    "settings.privacy": ["Privacy policy", "プライバシーポリシー", "Política de privacidad", "Politique de confidentialité", "Datenschutzrichtlinie", "Informativa sulla privacy", "Política de privacidade", "개인정보 처리방침", "隐私政策", "隱私權政策", "Политика конфиденциальности"],
    "settings.privacy_choices": ["Privacy choices", "プライバシー設定", "Opciones de privacidad", "Choix de confidentialité", "Datenschutzauswahl", "Scelte sulla privacy", "Escolhas de privacidade", "개인정보 선택", "隐私选项", "隱私選項", "Параметры конфиденциальности"],
    "settings.remove_ads": ["Remove Ads", "広告を削除", "Quitar anuncios", "Supprimer les publicités", "Werbung entfernen", "Rimuovi annunci", "Remover anúncios", "광고 제거", "移除广告", "移除廣告", "Отключить рекламу"],
    "settings.remove_ads_footer": ["One-time purchase. Removes banner ads from Colorvia forever.", "一度のお支払いで、Colorviaのバナー広告を永久に非表示にします。", "Compra única. Elimina los anuncios de banner de Colorvia para siempre.", "Achat unique. Supprime définitivement les publicités bannières de Colorvia.", "Einmaliger Kauf. Entfernt Banner-Werbung dauerhaft aus Colorvia.", "Acquisto una tantum. Rimuove per sempre gli annunci banner da Colorvia.", "Compra única. Remove os anúncios em banner do Colorvia para sempre.", "1회 구매로 Colorvia의 배너 광고를 영구히 제거합니다.", "一次性购买，永久移除 Colorvia 中的横幅广告。", "一次性購買，永久移除 Colorvia 中的橫幅廣告。", "Единоразовая покупка. Полностью удаляет баннерную рекламу из Colorvia."],
    "settings.remove_ads_thanks_message": ["Thanks for your support! Colorvia is ad-free on this device.", "ご購入ありがとうございます。この端末では広告なしでColorviaをご利用いただけます。", "¡Gracias por tu apoyo! Colorvia no muestra anuncios en este dispositivo.", "Merci pour votre soutien ! Colorvia est sans publicité sur cet appareil.", "Danke für deine Unterstützung! Colorvia ist auf diesem Gerät werbefrei.", "Grazie per il tuo supporto! Colorvia è senza pubblicità su questo dispositivo.", "Obrigado pelo seu apoio! O Colorvia não exibe anúncios neste dispositivo.", "후원해 주셔서 감사합니다! 이 기기에서는 Colorvia에 광고가 표시되지 않습니다.", "感谢您的支持！此设备上的 Colorvia 将不再显示广告。", "感謝您的支持！此裝置上的 Colorvia 將不再顯示廣告。", "Спасибо за поддержку! На этом устройстве Colorvia работает без рекламы."],
    "settings.remove_ads_thanks_title": ["Ads Removed", "広告を削除済み", "Anuncios eliminados", "Publicités supprimées", "Werbung entfernt", "Annunci rimossi", "Anúncios removidos", "광고 제거됨", "已移除广告", "已移除廣告", "Реклама отключена"],
    "settings.reset_all": ["Delete all visit data", "すべての訪問データを削除", "Eliminar todos los datos de visitas", "Supprimer toutes les visites", "Alle Besuchsdaten löschen", "Elimina tutti i dati delle visite", "Excluir todos os dados de visita", "모든 방문 데이터 삭제", "删除所有访问数据", "刪除所有造訪資料", "Удалить все данные о посещениях"],
    "settings.reset_confirm": ["Delete your visit data?", "訪問データを削除しますか？", "¿Eliminar los datos de visitas?", "Supprimer vos visites ?", "Besuchsdaten löschen?", "Eliminare i dati delle visite?", "Excluir os dados de visita?", "방문 데이터를 삭제할까요?", "删除访问数据？", "刪除造訪資料？", "Удалить данные о посещениях?"],
    "settings.restore_purchases": ["Restore Purchases", "購入を復元", "Restaurar compras", "Restaurer les achats", "Käufe wiederherstellen", "Ripristina acquisti", "Restaurar compras", "구매 복원", "恢复购买", "恢復購買", "Восстановить покупки"],
    "settings.singapore_ura_description": bilingual(
        "Master Plan 2019 Planning Area Boundary data, provided under the Singapore Open Data Licence.",
        "Master Plan 2019 Planning Area Boundaryデータ（Singapore Open Data Licence）。",
    ),
    "settings.support": ["Support", "サポート", "Ayuda", "Assistance", "Support", "Supporto", "Suporte", "지원", "支持", "支援", "Поддержка"],
    "settings.terms": ["Terms of use", "利用規約", "Términos de uso", "Conditions d’utilisation", "Nutzungsbedingungen", "Termini di utilizzo", "Termos de uso", "이용 약관", "使用条款", "使用條款", "Условия использования"],
    "settings.theme": ["Theme", "テーマ管理", "Tema", "Thème", "Design", "Tema", "Tema", "테마", "主题", "主題", "Тема"],
    "settings.title": ["Settings", "設定", "Ajustes", "Réglages", "Einstellungen", "Impostazioni", "Ajustes", "설정", "设置", "設定", "Настройки"],
    "settings.updates": ["What’s new", "アップデート情報", "Novedades", "Nouveautés", "Neuigkeiten", "Novità", "Novidades", "업데이트 정보", "更新信息", "更新資訊", "Что нового"],
    "settings.us_census_description": bilingual(
        "2024 state-equivalent cartographic boundary data for the United States map.",
        "アメリカ合衆国地図向けの2024年版州相当カートン境界データ。",
    ),
    "settings.version": ["Version information", "バージョン情報", "Información de versión", "Informations de version", "Versionsinformationen", "Informazioni sulla versione", "Informações da versão", "버전 정보", "版本信息", "版本資訊", "Информация о версии"],
    "settings.view_source": ["View data source", "データ提供元を見る", "Ver fuente de datos", "Voir la source des données", "Datenquelle anzeigen", "Visualizza origine dati", "Ver fonte dos dados", "데이터 출처 보기", "查看数据来源", "查看資料來源", "Открыть источник данных"],
    "stats.by_continent": ["By continent", "大陸別", "Por continente", "Par continent", "Nach Kontinent", "Per continente", "Por continente", "대륙별", "按大洲", "依洲別", "По континентам"],
    "stats.close": ["Collapse statistics", "統計を閉じる", "Contraer estadísticas", "Réduire les statistiques", "Statistik schließen", "Chiudi statistiche", "Recolher estatísticas", "통계 닫기", "收起统计", "收合統計", "Свернуть статистику"],
    "stats.no_countries": ["No countries visited yet", "訪れた国はまだありません", "Aún no hay países visitados", "Aucun pays visité", "Noch keine Länder besucht", "Nessun paese visitato", "Nenhum país visitado ainda", "아직 방문한 국가가 없어요", "尚无到访国家", "尚無造訪國家", "Пока нет посещённых стран"],
    "stats.open": ["Expand statistics", "統計を開く", "Ampliar estadísticas", "Développer les statistiques", "Statistik öffnen", "Apri statistiche", "Expandir estatísticas", "통계 열기", "展开统计", "展開統計", "Развернуть статистику"],
    "stats.swipe_up": ["Swipe up to see statistics", "上にスワイプして統計を表示", "Desliza hacia arriba para ver las estadísticas", "Balayez vers le haut pour voir les statistiques", "Nach oben wischen für Statistiken", "Scorri in alto per le statistiche", "Deslize para cima para ver as estatísticas", "위로 쓸어올려 통계 보기", "向上滑动查看统计", "向上滑動查看統計", "Проведите вверх, чтобы увидеть статистику"],
    "stats.title": ["Your world", "あなたの世界", "Tu mundo", "Votre monde", "Deine Welt", "Il tuo mondo", "Seu mundo", "나의 세계", "你的世界", "你的世界", "Ваш мир"],
    "stats.visited_countries": ["Visited countries", "訪れた国", "Países visitados", "Pays visités", "Besuchte Länder", "Paesi visitati", "Países visitados", "방문한 국가", "到访国家", "造訪國家", "Посещённые страны"],
    "stats.world_percentage": ["World explored", "世界の割合", "Mundo explorado", "Monde exploré", "Erkundete Welt", "Mondo esplorato", "Mundo explorado", "탐험한 세계", "探索世界比例", "探索世界比例", "Исследовано мира"],
    "subdivision.choose": bilingual("Choose regions", "地域を選ぶ"),
    "subdivision.map_accessibility": bilingual("Read-only regional map", "閲覧専用の地域マップ"),
    "subdivision.open_map": bilingual("Open regional map", "地域マップを開く"),
    "subdivision.parent_required": bilingual(
        "To use the regional map, mark this country as visited first.",
        "地域マップを利用するには、先にこの国を訪問済みにしてください。",
    ),
    "subdivision.progress": bilingual("Regional progress", "地域の進捗"),
    "subdivision.regions": bilingual("Regions", "地域"),
    "subdivision.remove_all": bilingual("Remove country and all regions", "国と地域をすべて外す"),
    "subdivision.search": bilingual("Region, city, or landmark", "地域名・都市名・観光地"),
    "subdivision_share.country_map": bilingual("Country map", "地域マップ"),
    "subdivision_share.map_only": bilingual("Map only", "地図のみ"),
    "subdivision_share.square": bilingual("Square poster", "正方形ポスター"),
    "subdivision_share.story": bilingual("Story poster", "ストーリーポスター"),
    "subdivision_share.title": bilingual("Share regional map", "地域マップを共有"),
    "unit.countries": ["countries", "か国", "países", "pays", "Länder", "paesi", "países", "개국", "个国家", "個國家", "стран"],
    "unit.country_one": ["country", "か国", "país", "pays", "Land", "paese", "país", "개국", "个国家", "個國家", "страна"],
    "unit.prefectures": bilingual("prefectures", "都道府県"),
    "unit.regions": bilingual("regions", "地域"),
    "updates.earlier": ["Earlier release", "過去のバージョン", "Versión anterior", "Version précédente", "Frühere Version", "Versione precedente", "Versão anterior", "이전 버전", "历史版本", "歷史版本", "Предыдущая версия"],
    "updates.intro": ["A version-by-version record of what changed in Colorvia.", "Colorviaの変更を、バージョンごとに記録しています。", "Un registro de los cambios de Colorvia, versión a versión.", "L’historique des changements de Colorvia, version par version.", "Eine Aufzeichnung der Änderungen in Colorvia, Version für Version.", "Un registro delle modifiche di Colorvia, versione per versione.", "Um registro das mudanças do Colorvia, versão por versão.", "버전별로 Colorvia의 변경 사항을 기록합니다.", "按版本记录 Colorvia 的更新内容。", "依版本記錄 Colorvia 的更新內容。", "Список изменений Colorvia по версиям."],
    "updates.latest": ["Latest", "最新", "Última", "Dernière", "Aktuell", "Ultima", "Mais recente", "최신", "最新", "最新", "Последняя"],
    "updates.v1_0_0.change1": ["Colour a world map by marking the countries you’ve visited", "訪れた国を選んで世界地図を塗る", "Colorea el mapamundi con los países visitados", "Coloriez la carte du monde selon les pays visités", "Weltkarte nach besuchten Ländern einfärben", "Colora il planisfero con i paesi visitati", "Pinte o mapa-múndi com os países visitados", "방문한 나라를 선택해 세계 지도 색칠", "选择去过的国家为世界地图上色", "選擇去過的國家為世界地圖上色", "Раскрашивание карты мира по посещённым странам"],
    "updates.v1_0_0.change2": ["Record prefectures, states and provinces in 11 supported countries", "対応11か国で都道府県・州などを記録", "Registra regiones en 11 países compatibles", "Enregistrez les régions dans 11 pays pris en charge", "Regionen in 11 unterstützten Ländern erfassen", "Registra le regioni in 11 paesi supportati", "Registre regiões em 11 países compatíveis", "지원되는 11개국의 지역 단위 기록", "在 11 个支持的国家记录国内地区", "在 11 個支援的國家記錄國內地區", "Регионы в 11 поддерживаемых странах"],
    "updates.v1_0_0.change3": ["Statistics such as visit counts and world percentage", "訪問数・世界の訪問率などの統計", "Estadísticas como visitas y porcentaje mundial", "Statistiques : nombre de visites, pourcentage du monde", "Statistiken wie Anzahl und Weltanteil", "Statistiche come visite e percentuale mondiale", "Estatísticas como visitas e porcentagem do mundo", "방문 수와 세계 방문율 등 통계", "访问数量与世界覆盖率等统计", "造訪數量與世界覆蓋率等統計", "Статистика: число посещений и доля мира"],
    "updates.v1_0_0.change4": ["Place search, plus theme and map colour options", "地名検索、テーマと地図色の変更", "Búsqueda de lugares, temas y colores de mapa", "Recherche de lieux, thèmes et couleurs de carte", "Ortssuche sowie Themen- und Kartenfarben", "Ricerca luoghi, temi e colori della mappa", "Busca de lugares, temas e cores do mapa", "지명 검색, 테마와 지도 색 변경", "地名搜索、主题与地图配色", "地名搜尋、主題與地圖配色", "Поиск мест, темы и цвета карты"],
    "updates.v1_0_0.change5": ["Export and import your records as JSON", "JSONで書き出し・読み込み", "Exporta e importa tus datos en JSON", "Exportez et importez vos données en JSON", "Daten als JSON exportieren und importieren", "Esporta e importa i dati in JSON", "Exporte e importe seus dados em JSON", "JSON으로 내보내기・가져오기", "以 JSON 导出与导入", "以 JSON 匯出與匯入", "Экспорт и импорт данных в JSON"],
    "updates.v1_0_0.change6": ["Works offline", "オフライン対応", "Funciona sin conexión", "Fonctionne hors ligne", "Funktioniert offline", "Funziona offline", "Funciona offline", "오프라인 지원", "支持离线使用", "支援離線使用", "Работает офлайн"],
    "updates.v1_0_0.change7": ["A one-time “Remove Ads” purchase", "買い切りの「広告を削除」", "Compra única “Eliminar anuncios”", "Achat unique « Supprimer les publicités »", "Einmalkauf „Werbung entfernen“", "Acquisto una tantum “Rimuovi pubblicità”", "Compra única “Remover anúncios”", "1회 구매 ‘광고 제거’", "一次性购买“移除广告”", "一次性購買「移除廣告」", "Разовая покупка «Убрать рекламу»"],
    "updates.v1_0_0.summary": ["The first version of Colorvia. Colour a world map by the countries you’ve visited, and go beyond countries in 11 supported ones.", "Colorviaの最初のバージョンです。訪れた国を選んで世界地図を彩り、対応11か国では国の内側まで記録できます。", "La primera versión de Colorvia. Colorea el mapamundi con los países que has visitado y, en 11 de ellos, también sus regiones.", "La première version de Colorvia. Coloriez la carte du monde selon les pays visités, et allez plus loin dans 11 pays.", "Die erste Version von Colorvia. Färben Sie die Weltkarte nach besuchten Ländern – in 11 Ländern auch innerhalb des Landes.", "La prima versione di Colorvia. Colora il planisfero con i paesi visitati e, in 11 di essi, anche le regioni.", "A primeira versão do Colorvia. Pinte o mapa-múndi com os países visitados e, em 11 deles, também as regiões.", "Colorvia의 첫 번째 버전입니다. 방문한 나라로 세계 지도를 칠하고, 지원되는 11개국에서는 국내 지역까지 기록할 수 있습니다.", "Colorvia 的首个版本。选择去过的国家为世界地图上色，在 11 个国家还可记录国内地区。", "Colorvia 的首個版本。選擇去過的國家為世界地圖上色，在 11 個國家還可記錄國內地區。", "Первая версия Colorvia. Раскрашивайте карту мира по посещённым странам, а в 11 странах — и регионы внутри них."],
    "updates.v1_0_1.change1": ["Reworked contact form with a type of enquiry to choose from", "お問い合わせフォームを刷新し、種類を選べるように", "Formulario de contacto renovado, con tipo de consulta", "Formulaire de contact repensé, avec un type de demande", "Kontaktformular überarbeitet: Art der Anfrage wählbar", "Modulo di contatto rinnovato, con tipo di richiesta", "Formulário de contato renovado, com tipo de solicitação", "문의 유형을 선택할 수 있도록 문의 양식 개편", "重做咨询表单，可选择咨询类型", "重做諮詢表單，可選擇諮詢類型", "Обновлённая форма обращения с выбором типа"],
    "updates.v1_0_1.change2": ["An email address is now asked for only when you want a reply", "返信をご希望の場合のみメールアドレスを伺うように", "Solo se pide el correo electrónico si quieres respuesta", "L’adresse e-mail n’est demandée que si vous souhaitez une réponse", "E-Mail-Adresse nur noch nötig, wenn Sie eine Antwort möchten", "L’indirizzo e-mail viene chiesto solo se desideri una risposta", "O e-mail só é solicitado quando você quer resposta", "답변을 원하실 때만 이메일 주소를 요청", "仅在您希望收到回复时才需要填写电子邮件地址", "僅在您希望收到回覆時才需要填寫電子郵件地址", "Адрес эл. почты запрашивается, только если вы ждёте ответ"],
    "updates.v1_0_1.change3": ["The bundled Privacy Policy and Terms now match the website word for word", "同梱のプライバシーポリシーと利用規約をWeb版と同じ内容に更新", "La Política de privacidad y los Términos incluidos coinciden con la web", "La politique de confidentialité et les CGU incluses correspondent au site", "Mitgelieferte Datenschutzerklärung und Nutzungsbedingungen auf dem Stand der Website", "Informativa sulla privacy e Termini inclusi allineati al sito", "Política de Privacidade e Termos incluídos agora iguais aos do site", "앱에 포함된 개인정보 처리방침과 이용약관을 웹과 동일한 내용으로 갱신", "应用内附带的隐私政策与使用条款已与网站一致", "應用程式內附的隱私權政策與使用條款已與網站一致", "Встроенные политика конфиденциальности и условия совпадают с сайтом"],
    "updates.v1_0_1.change4": ["The offline notice now says the website version is the authoritative one", "オフライン表示に、正本がWeb版である旨を明記", "El aviso sin conexión indica que la versión web es la oficial", "L’avis hors ligne précise que la version du site fait foi", "Offline-Hinweis nennt die Website als maßgebliche Fassung", "L’avviso offline indica che la versione del sito fa fede", "O aviso offline informa que a versão do site é a oficial", "오프라인 안내에 웹 버전이 정본임을 명시", "离线提示中注明网站版本为正式版本", "離線提示中註明網站版本為正式版本", "В офлайн-уведомлении указано, что версия на сайте — основная"],
    "updates.v1_0_1.change5": ["A redesigned What’s New screen", "「アップデート情報」の画面を刷新", "Pantalla de novedades rediseñada", "Écran des nouveautés repensé", "Überarbeiteter Bildschirm „Neuerungen“", "Schermata delle novità ridisegnata", "Tela de novidades redesenhada", "‘업데이트 정보’ 화면 개편", "重新设计“更新信息”页面", "重新設計「更新資訊」頁面", "Переработанный экран «Что нового»"],
    "updates.v1_0_1.change6": ["Small wording and label corrections", "細かな表記の修正", "Pequeñas correcciones de textos", "Petites corrections de libellés", "Kleinere Korrekturen an Beschriftungen", "Piccole correzioni ai testi", "Pequenas correções de textos", "세부 표기 수정", "细节文案修正", "細節文案修正", "Мелкие исправления в подписях"],
    "updates.v1_0_1.summary": ["Improvements to the contact form and to the legal documents bundled with the app.", "お問い合わせフォームと、アプリに同梱している法務文書まわりの改善です。", "Mejoras en el formulario de contacto y en los documentos legales incluidos en la app.", "Améliorations du formulaire de contact et des documents juridiques inclus dans l’app.", "Verbesserungen am Kontaktformular und an den in der App mitgelieferten Rechtstexten.", "Miglioramenti al modulo di contatto e ai documenti legali inclusi nell’app.", "Melhorias no formulário de contato e nos documentos legais incluídos no app.", "문의 양식과 앱에 포함된 법률 문서를 개선했습니다.", "改进了咨询表单，以及应用内附带的法律文件。", "改善了諮詢表單，以及應用程式內附的法律文件。", "Улучшения формы обращения и юридических документов, входящих в приложение."],
}


def main():
    strings = {}
    for key, values in STRINGS.items():
        if len(values) != len(LANGUAGES):
            raise ValueError(f"{key}: expected {len(LANGUAGES)} translations, got {len(values)}")
        strings[key] = {
            "extractionState": "manual",
            "localizations": {
                language: {"stringUnit": {"state": "translated", "value": value}}
                for language, value in zip(LANGUAGES, values)
            },
        }

    output = Path("Colorvia/Resources/Localizable.xcstrings")
    output.write_text(
        json.dumps(
            {"sourceLanguage": "en", "strings": strings, "version": "1.0"},
            ensure_ascii=False,
            indent=2,
        )
        + "\n"
    )
    print(f"Wrote {len(strings)} keys in {len(LANGUAGES)} languages to {output}")


if __name__ == "__main__":
    main()
