#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Colorvia's String Catalog from reviewed in-repository translations."""

import json
from pathlib import Path


LANGUAGES = ["en", "ja", "es", "fr", "de", "it", "pt-BR", "ko", "zh-Hans", "zh-Hant", "ru"]


def bilingual(english, japanese):
    """Use reviewed Japanese copy and an English fallback for other locales."""
    return [english, japanese] + [english] * (len(LANGUAGES) - 2)


# Values are ordered according to LANGUAGES.
STRINGS = {
    "common.cancel": ["Cancel", "キャンセル", "Cancelar", "Annuler", "Abbrechen", "Annulla", "Cancelar", "취소", "取消", "取消", "Отмена"],
    "common.close": ["Close", "閉じる", "Cerrar", "Fermer", "Schließen", "Chiudi", "Fechar", "닫기", "关闭", "關閉", "Закрыть"],
    "common.delete": ["Delete", "削除", "Eliminar", "Supprimer", "Löschen", "Elimina", "Excluir", "삭제", "删除", "刪除", "Удалить"],
    "common.share": ["Share", "共有", "Compartir", "Partager", "Teilen", "Condividi", "Compartilhar", "공유", "分享", "分享", "Поделиться"],
    "country_detail.code": bilingual("Country code", "国コード"),
    "country_detail.continent": bilingual("Continent", "大陸"),
    "country_detail.status": bilingual("Visit status", "訪問状態"),
    "country_list.remove_visited": bilingual("Remove from visited", "訪問済みから外す"),
    "country_list.title": bilingual("Choose countries", "国を選ぶ"),
    "contact.email_placeholder": ["Reply email address", "返信先メールアドレス", "Correo electrónico de respuesta", "Adresse e-mail de réponse", "E-Mail-Adresse für Antworten", "Indirizzo email per la risposta", "E-mail para resposta", "답변받을 이메일 주소", "回复电子邮件地址", "回覆電子郵件地址", "Адрес электронной почты для ответа"],
    "contact.footer": ["This preview form keeps its contents on this device.", "このモックフォームの入力内容は端末内だけで扱われます。", "Este formulario de muestra conserva el contenido en el dispositivo.", "Ce formulaire de démonstration conserve son contenu sur l’appareil.", "Dieses Vorschauformular speichert Inhalte nur auf diesem Gerät.", "Questo modulo di anteprima conserva i dati sul dispositivo.", "Este formulário de demonstração mantém o conteúdo no dispositivo.", "이 미리보기 양식의 내용은 기기에만 보관됩니다.", "此预览表单的内容仅保留在设备上。", "此預覽表單的內容只會保留在裝置上。", "Данные этой демонстрационной формы остаются на устройстве."],
    "contact.form_title": ["Send us a message", "メッセージを送る", "Envíanos un mensaje", "Envoyez-nous un message", "Nachricht senden", "Inviaci un messaggio", "Envie uma mensagem", "메시지 보내기", "发送消息", "傳送訊息", "Отправить сообщение"],
    "contact.message_placeholder": ["How can we help?", "お問合せ内容", "¿Cómo podemos ayudarte?", "Comment pouvons-nous vous aider ?", "Wie können wir helfen?", "Come possiamo aiutarti?", "Como podemos ajudar?", "무엇을 도와드릴까요?", "我们能为你做什么？", "我們能為你做什麼？", "Чем мы можем помочь?"],
    "contact.send": ["Preview submission", "送信をプレビュー", "Vista previa del envío", "Aperçu de l’envoi", "Senden als Vorschau", "Anteprima invio", "Visualizar envio", "전송 미리보기", "预览提交", "預覽送出", "Предпросмотр отправки"],
    "contact.sent_body": ["This is a mock support form. No message was transmitted.", "これはサポートフォームのモックです。メッセージは送信されていません。", "Este es un formulario de muestra. No se envió ningún mensaje.", "Ceci est un formulaire fictif. Aucun message n’a été envoyé.", "Dies ist ein Musterformular. Es wurde keine Nachricht gesendet.", "Questo è un modulo dimostrativo. Nessun messaggio è stato inviato.", "Este é um formulário de demonstração. Nenhuma mensagem foi enviada.", "지원 양식 목업입니다. 메시지는 전송되지 않았습니다.", "这是支持表单模型，未发送任何消息。", "這是支援表單模型，未傳送任何訊息。", "Это макет формы поддержки. Сообщение не отправлено."],
    "contact.sent_title": ["Preview complete", "プレビュー完了", "Vista previa lista", "Aperçu terminé", "Vorschau abgeschlossen", "Anteprima completata", "Visualização concluída", "미리보기 완료", "预览完成", "預覽完成", "Предпросмотр завершён"],
    "continent.africa": ["Africa", "アフリカ", "África", "Afrique", "Afrika", "Africa", "África", "아프리카", "非洲", "非洲", "Африка"],
    "continent.asia": ["Asia", "アジア", "Asia", "Asie", "Asien", "Asia", "Ásia", "아시아", "亚洲", "亞洲", "Азия"],
    "continent.europe": ["Europe", "ヨーロッパ", "Europa", "Europe", "Europa", "Europa", "Europa", "유럽", "欧洲", "歐洲", "Европа"],
    "continent.north_america": ["North America", "北アメリカ", "Norteamérica", "Amérique du Nord", "Nordamerika", "Nord America", "América do Norte", "북아메리카", "北美洲", "北美洲", "Северная Америка"],
    "continent.oceania": ["Oceania", "オセアニア", "Oceanía", "Océanie", "Ozeanien", "Oceania", "Oceania", "오세아니아", "大洋洲", "大洋洲", "Океания"],
    "continent.south_america": ["South America", "南アメリカ", "Sudamérica", "Amérique du Sud", "Südamerika", "Sud America", "América do Sul", "남아메리카", "南美洲", "南美洲", "Южная Америка"],
    "format.country_count": ["%d countries", "%dか国", "%d países", "%d pays", "%d Länder", "%d paesi", "%d países", "%d개국", "%d个国家", "%d 個國家", "%d стран"],
    "format.country_count_one": ["1 country", "1か国", "1 país", "1 pays", "1 Land", "1 paese", "1 país", "1개국", "1个国家", "1 個國家", "1 страна"],
    "format.japan_explored": bilingual("Japan explored: %@%%", "日本の探索率：%@%%"),
    "format.japan_row_unvisited": bilingual("Not visited · %d / 47 prefectures", "未訪問・%d / 47都道府県"),
    "format.japan_row_visited": bilingual("Visited · %d / 47 prefectures", "訪問済み・%d / 47都道府県"),
    "format.japan_share_message": bilingual("I have visited %d prefectures in Japan with Colorvia.", "Colorviaで日本の%d都道府県を訪れました。"),
    "format.map_visited": ["%d countries visited", "%dか国を訪問済み", "%d países visitados", "%d pays visités", "%d Länder besucht", "%d paesi visitati", "%d países visitados", "%d개국 방문", "已访问%d个国家", "已造訪 %d 個國家", "Посещено стран: %d"],
    "format.number": bilingual("%d", "%d"),
    "format.percentage": bilingual("%@%%", "%@%%"),
    "format.prefecture_fraction": bilingual("%d / 47", "%d / 47"),
    "format.france_department_fraction": bilingual("%d / 101 departments", "%d / 101 地域"),
    "format.france_row_unvisited": bilingual("Not visited · %d / 101 departments", "未訪問・%d / 101地域"),
    "format.france_row_visited": bilingual("Visited · %d / 101 departments", "訪問済み・%d / 101地域"),
    "format.france_share_message": bilingual("I have visited %d departments in France with Colorvia.", "Colorviaでフランスの%d地域を訪れました。"),
    "format.place_match_reason": bilingual("Matches %@", "%@に一致"),
    "format.remove_country_prompt": bilingual("Remove %@ from visited?", "%@を訪問済みから外しますか？"),
    "format.remove_france_message": bilingual("%d saved regions will also be removed.", "登録されている%d件の地域も訪問済みから外されます。"),
    "format.remove_japan_message": bilingual("%d saved prefectures will also be removed.", "登録されている%d件の都道府県も訪問済みから外されます。"),
    "format.selected_count": ["Done (%d)", "完了（%d）", "Listo (%d)", "Terminé (%d)", "Fertig (%d)", "Fine (%d)", "Concluir (%d)", "완료 (%d)", "完成（%d）", "完成（%d）", "Готово (%d)"],
    "format.selected_department_count": bilingual("Done (%d)", "完了（%d）"),
    "format.selected_prefecture_count": bilingual("Done (%d)", "完了（%d）"),
    "format.selected_subdivision_count": bilingual("Done (%d)", "完了（%d）"),
    "format.subdivision_row_unvisited": bilingual("Not visited · %d / %d regions", "未訪問・%d / %d地域"),
    "format.subdivision_row_visited": bilingual("Visited · %d / %d regions", "訪問済み・%d / %d地域"),
    "format.remove_subdivision_message": bilingual("%d saved regions will also be removed.", "登録されている%d件の地域も訪問済みから外されます。"),
    "format.share_message": ["I have visited %d countries with Colorvia.", "Colorviaで%dか国を訪れました。", "He visitado %d países con Colorvia.", "J’ai visité %d pays avec Colorvia.", "Ich habe mit Colorvia %d Länder besucht.", "Ho visitato %d paesi con Colorvia.", "Visitei %d países com o Colorvia.", "Colorvia로 %d개국을 방문했어요.", "我用Colorvia记录了%d个到访国家。", "我用 Colorvia 記錄了 %d 個造訪國家。", "Я посетил(а) %d стран с Colorvia."],
    "format.visited_country_summary": bilingual("%d countries visited", "%dか国を訪問済み"),
    "format.visited_department_summary": bilingual("%d departments visited", "%d地域"),
    "format.visited_prefecture_summary": bilingual("%d prefectures visited", "%d都道府県"),
    "filter.all": bilingual("All", "すべて"),
    "filter.title": bilingual("Filter", "フィルター"),
    "filter.unvisited": bilingual("Not visited", "未訪問"),
    "filter.visited": bilingual("Visited", "訪問済み"),
    "france.flag": bilingual("🇫🇷", "🇫🇷"),
    "france_detail.department_progress": bilingual("Department progress", "地域の進捗"),
    "france_detail.open_map": bilingual("Open France map", "フランス地図を開く"),
    "france_detail.remove_all": bilingual("Remove France and all regions", "フランスと地域をすべて外す"),
    "france_detail.remove_prompt": bilingual("Remove France from visited?", "フランスを訪問済みから外しますか？"),
    "france_list.choose": bilingual("Choose regions", "地域を選ぶ"),
    "france_list.search": bilingual("Department, city, or code", "地域名・都市名・コード"),
    "france_list.title": bilingual("Choose regions", "フランスの地域を選ぶ"),
    "france_share.departments": bilingual("DEPARTMENTS", "地域"),
    "france_share.percentage_prefix": bilingual("France explored: ", "フランスの"),
    "france_share.poster_title": bilingual("MY FRANCE", "わたしのフランス地図"),
    "france_share.square": bilingual("Square poster", "正方形ポスター"),
    "france_share.story": bilingual("Story poster", "ストーリーポスター"),
    "france_share.title": bilingual("Share France map", "フランス地図を共有"),
    "france_map.accessibility_label": bilingual("Map of France departments", "フランス地域地図"),
    "france_stats.title": bilingual("Your France", "あなたのフランス"),
    "faq.account.body": ["No. Colorvia works without creating an account.", "いいえ。Colorviaはアカウントを作成せずに利用できます。", "No. Colorvia funciona sin crear una cuenta.", "Non. Colorvia fonctionne sans créer de compte.", "Nein. Colorvia funktioniert ohne Konto.", "No. Colorvia funziona senza creare un account.", "Não. O Colorvia funciona sem criar uma conta.", "아니요. 계정을 만들지 않고 사용할 수 있습니다.", "不需要。Colorvia无需创建账户即可使用。", "不需要。Colorvia 無須建立帳號即可使用。", "Нет. Colorvia работает без учётной записи."],
    "faq.account.title": ["Do I need an account?", "アカウントは必要ですか？", "¿Necesito una cuenta?", "Ai-je besoin d’un compte ?", "Brauche ich ein Konto?", "Serve un account?", "Preciso de uma conta?", "계정이 필요한가요?", "需要账户吗？", "需要帳號嗎？", "Нужна ли учётная запись?"],
    "faq.percentage.body": ["The percentage is calculated against the 195 countries defined by Colorvia.", "Colorviaが定義する195か国を基準に計算しています。", "El porcentaje se calcula sobre los 195 países definidos por Colorvia.", "Le pourcentage est calculé sur les 195 pays définis par Colorvia.", "Der Prozentsatz basiert auf den 195 von Colorvia definierten Ländern.", "La percentuale è calcolata sui 195 paesi definiti da Colorvia.", "A porcentagem é calculada com base nos 195 países definidos pelo Colorvia.", "Colorvia가 정의한 195개국을 기준으로 계산합니다.", "百分比以Colorvia定义的195个国家为基准计算。", "百分比以 Colorvia 定義的 195 個國家為基準計算。", "Процент рассчитывается относительно 195 стран, определённых Colorvia."],
    "faq.percentage.title": ["How is the percentage calculated?", "世界割合はどう計算されますか？", "¿Cómo se calcula el porcentaje?", "Comment le pourcentage est-il calculé ?", "Wie wird der Prozentsatz berechnet?", "Come viene calcolata la percentuale?", "Como a porcentagem é calculada?", "세계 비율은 어떻게 계산하나요?", "世界比例如何计算？", "世界比例如何計算？", "Как рассчитывается процент?"],
    "faq.storage.body": ["Visit data is stored locally on your device.", "訪問データは端末内に保存されます。", "Los datos se guardan localmente en el dispositivo.", "Les visites sont stockées localement sur votre appareil.", "Besuchsdaten werden lokal auf dem Gerät gespeichert.", "I dati sono salvati localmente sul dispositivo.", "Os dados são armazenados localmente no dispositivo.", "방문 데이터는 기기에 저장됩니다.", "访问数据存储在你的设备上。", "造訪資料會儲存在你的裝置上。", "Данные хранятся локально на устройстве."],
    "faq.storage.title": ["Where is my data stored?", "データはどこに保存されますか？", "¿Dónde se guardan mis datos?", "Où mes données sont-elles stockées ?", "Wo werden meine Daten gespeichert?", "Dove vengono salvati i dati?", "Onde meus dados são armazenados?", "데이터는 어디에 저장되나요?", "数据存储在哪里？", "資料儲存在哪裡？", "Где хранятся данные?"],
    "guide.add.body": ["Tap the plus button, search for a country, and mark it as visited.", "＋ボタンを押し、国を検索して訪問済みにします。", "Toca el botón más, busca un país y márcalo como visitado.", "Touchez le bouton plus, recherchez un pays et marquez-le comme visité.", "Tippe auf Plus, suche ein Land und markiere es als besucht.", "Tocca il pulsante più, cerca un paese e segnalo come visitato.", "Toque no botão de mais, procure um país e marque como visitado.", "＋ 버튼을 누르고 국가를 검색해 방문한 국가로 표시하세요.", "点击加号按钮，搜索国家并标记为已访问。", "點一下加號按鈕，搜尋國家並標記為已造訪。", "Нажмите плюс, найдите страну и отметьте её как посещённую."],
    "guide.add.title": ["Add a country", "国を追加する", "Añadir un país", "Ajouter un pays", "Land hinzufügen", "Aggiungi un paese", "Adicionar um país", "국가 추가", "添加国家", "新增國家", "Добавление страны"],
    "guide.map.body": ["Pinch to zoom, drag to move, or use the map controls to reset the view.", "ピンチで拡大し、ドラッグで移動できます。操作ボタンから初期表示へ戻せます。", "Pellizca para ampliar, arrastra para mover o usa los controles para restablecer.", "Pincez pour zoomer, faites glisser pour déplacer ou utilisez les commandes.", "Zoome mit zwei Fingern, verschiebe die Karte oder setze sie über die Steuerung zurück.", "Pizzica per ingrandire, trascina per spostare o usa i comandi.", "Use o gesto de pinça para ampliar, arraste para mover ou use os controles.", "손가락으로 확대하고 드래그해 이동하거나 지도 버튼으로 초기화하세요.", "双指缩放、拖动地图，或使用地图控件重置视图。", "雙指縮放、拖曳地圖，或使用地圖控制項目重設顯示。", "Масштабируйте жестом, перемещайте карту или используйте кнопки сброса."],
    "guide.map.title": ["Explore the map", "地図を操作する", "Explorar el mapa", "Explorer la carte", "Karte erkunden", "Esplora la mappa", "Explorar o mapa", "지도 둘러보기", "浏览地图", "瀏覽地圖", "Работа с картой"],
    "guide.start.body": ["Colorvia colors the countries you have visited and keeps a simple record of your world.", "Colorviaは訪れた国を色づけ、自分の世界をシンプルに記録します。", "Colorvia colorea los países que has visitado y registra tu mundo.", "Colorvia colore les pays visités et conserve une trace simple de votre monde.", "Colorvia färbt besuchte Länder und hält deine Welt einfach fest.", "Colorvia colora i paesi visitati e registra il tuo mondo.", "O Colorvia colore os países visitados e registra o seu mundo.", "Colorvia는 방문한 국가를 색칠해 나의 세계를 기록합니다.", "Colorvia为你去过的国家上色，简单记录你的世界。", "Colorvia 為你去過的國家上色，簡單記錄你的世界。", "Colorvia раскрашивает посещённые страны и сохраняет вашу карту мира."],
    "guide.start.title": ["Getting started", "はじめに", "Primeros pasos", "Bien démarrer", "Erste Schritte", "Per iniziare", "Primeiros passos", "시작하기", "开始使用", "開始使用", "Начало работы"],
    "home.add_country": ["Add a visited country", "訪れた国を追加", "Añadir un país visitado", "Ajouter un pays visité", "Besuchtes Land hinzufügen", "Aggiungi un paese visitato", "Adicionar país visitado", "방문한 국가 추가", "添加到访国家", "新增造訪國家", "Добавить посещённую страну"],
    "japan_detail.mark_visited": bilingual("Mark as visited", "訪問済みにする"),
    "japan_detail.open_map": bilingual("Open prefecture map", "都道府県マップを開く"),
    "japan_detail.prefecture_progress": bilingual("Prefecture progress", "都道府県の進捗"),
    "japan_detail.remove_all": bilingual("Remove Japan and all prefectures", "日本と都道府県をすべて外す"),
    "japan_detail.remove_prompt": bilingual("Remove Japan from visited?", "日本を訪問済みから外しますか？"),
    "japan.flag": bilingual("🇯🇵", "🇯🇵"),
    "japan_map.accessibility_label": bilingual("Map of Japan", "日本地図"),
    "japan_stats.by_region": bilingual("By region", "地方別"),
    "japan_stats.no_prefectures": bilingual("No prefectures visited yet", "訪れた都道府県はまだありません"),
    "japan_stats.swipe_up": bilingual("Swipe up to see statistics", "上にスワイプして統計を表示"),
    "japan_stats.title": bilingual("Your Japan", "あなたの日本"),
    "japan_stats.visited_prefectures": bilingual("Visited prefectures", "訪れた都道府県"),
    "map.accessibility_label": ["World map", "世界地図", "Mapa mundial", "Carte du monde", "Weltkarte", "Mappa del mondo", "Mapa-múndi", "세계 지도", "世界地图", "世界地圖", "Карта мира"],
    "map.reset": ["Reset map", "地図をリセット", "Restablecer mapa", "Réinitialiser la carte", "Karte zurücksetzen", "Reimposta mappa", "Redefinir mapa", "지도 초기화", "重置地图", "重設地圖", "Сбросить карту"],
    "map.zoom_in": ["Zoom in", "拡大", "Acercar", "Zoom avant", "Vergrößern", "Ingrandisci", "Ampliar", "확대", "放大", "放大", "Приблизить"],
    "map.zoom_out": ["Zoom out", "縮小", "Alejar", "Zoom arrière", "Verkleinern", "Riduci", "Reduzir", "축소", "缩小", "縮小", "Отдалить"],
    "onboarding.choose_countries": ["Choose countries", "国を選ぶ", "Elegir países", "Choisir des pays", "Länder auswählen", "Scegli i paesi", "Escolher países", "국가 선택", "选择国家", "選擇國家", "Выбрать страны"],
    "onboarding.subtitle": ["Just choose the countries you have visited.", "行ったことのある国を選ぶだけ。", "Solo elige los países que has visitado.", "Choisissez simplement les pays visités.", "Wähle einfach die Länder aus, die du besucht hast.", "Scegli i paesi che hai visitato.", "Basta escolher os países que você visitou.", "가 본 국가를 선택하기만 하면 돼요.", "只需选择你去过的国家。", "只要選擇你去過的國家。", "Просто выберите страны, в которых вы побывали."],
    "onboarding.title": ["Color the world you have seen.", "訪れた世界を、色にしよう。", "Dale color al mundo que has visto.", "Mettez en couleur le monde que vous avez vu.", "Färbe die Welt, die du gesehen hast.", "Colora il mondo che hai visto.", "Dê cor ao mundo que você conheceu.", "내가 본 세계를 색칠해 보세요.", "为你看过的世界上色。", "為你看過的世界上色。", "Раскрасьте мир, который вы увидели."],
    "picker.search": ["Country name or code", "国名・国コード", "Nombre o código del país", "Nom ou code du pays", "Ländername oder Code", "Nome o codice del paese", "Nome ou código do país", "국가명 또는 국가 코드", "国家名称或代码", "國家名稱或代碼", "Название или код страны"],
    "picker.title": ["Choose visited countries", "訪れた国を選ぶ", "Elige los países visitados", "Choisir les pays visités", "Besuchte Länder auswählen", "Scegli i paesi visitati", "Escolha os países visitados", "방문한 국가 선택", "选择到访国家", "選擇造訪國家", "Выберите посещённые страны"],
    "prefecture_list.choose": bilingual("Choose prefectures", "都道府県を選ぶ"),
    "prefecture_list.search": bilingual("Prefecture name or code", "都道府県名・コード"),
    "prefecture_list.title": bilingual("Choose prefectures", "都道府県を選ぶ"),
    "region.chubu": bilingual("Chubu", "中部"),
    "region.chugoku": bilingual("Chugoku", "中国"),
    "region.hokkaido": bilingual("Hokkaido", "北海道"),
    "region.kanto": bilingual("Kanto", "関東"),
    "region.kinki": bilingual("Kinki", "近畿"),
    "region.kyushu_okinawa": bilingual("Kyushu & Okinawa", "九州・沖縄"),
    "region.shikoku": bilingual("Shikoku", "四国"),
    "region.tohoku": bilingual("Tohoku", "東北"),
    "settings.about": ["About", "アプリについて", "Acerca de", "À propos", "Über die App", "Informazioni", "Sobre", "앱 정보", "关于", "關於", "О приложении"],
    "settings.app_details": ["App details", "アプリ詳細", "Detalles de la app", "Détails de l’app", "App-Details", "Dettagli app", "Detalhes do app", "앱 상세 정보", "应用详情", "App 詳細資料", "Сведения о приложении"],
    "settings.app_studio": ["App studio", "アプリスタジオ", "Estudio de apps", "Studio d’apps", "App-Studio", "Studio app", "Estúdio de apps", "앱 스튜디오", "应用工作室", "App 工作室", "Студия приложений"],
    "settings.appearance": ["Appearance", "外観", "Apariencia", "Apparence", "Erscheinungsbild", "Aspetto", "Aparência", "화면 모드", "外观", "外觀", "Оформление"],
    "settings.appearance.light": ["Light", "ライト", "Claro", "Clair", "Hell", "Chiaro", "Claro", "라이트", "浅色", "淺色", "Светлое"],
    "settings.appearance.dark": ["Dark", "ダーク", "Oscuro", "Sombre", "Dunkel", "Scuro", "Escuro", "다크", "深色", "深色", "Тёмное"],
    "settings.appearance.system": ["System", "システム", "Sistema", "Système", "System", "Sistema", "Sistema", "시스템", "跟随系统", "跟隨系統", "Системное"],
    "settings.data": ["Data", "データ", "Datos", "Données", "Daten", "Dati", "Dados", "데이터", "数据", "資料", "Данные"],
    "settings.data_management": ["Data management", "データ管理", "Gestión de datos", "Gestion des données", "Datenverwaltung", "Gestione dati", "Gerenciamento de dados", "데이터 관리", "数据管理", "資料管理", "Управление данными"],
    "settings.data_management_footer": ["Deleting visit data cannot be undone.", "訪問データを削除すると元に戻せません。", "Los datos eliminados no se pueden recuperar.", "Les visites supprimées ne peuvent pas être restaurées.", "Gelöschte Besuchsdaten können nicht wiederhergestellt werden.", "I dati eliminati non possono essere ripristinati.", "Os dados excluídos não podem ser recuperados.", "삭제한 방문 데이터는 복구할 수 없습니다.", "删除的访问数据无法恢复。", "刪除的造訪資料無法復原。", "Удалённые данные нельзя восстановить."],
    "settings.export_json": bilingual("Export JSON", "JSONを書き出す"),
    "settings.import_complete": bilingual("Import complete", "読み込みが完了しました"),
    "settings.import_json": bilingual("Import JSON", "JSONを読み込む"),
    "settings.json_footer": bilingual("Export a backup or replace this device’s visit data from a Colorvia JSON file.", "バックアップを書き出すか、ColorviaのJSONファイルからこの端末の訪問データを置き換えます。"),
    "settings.developer": ["Developer", "開発", "Desarrollador", "Développeur", "Entwickler", "Sviluppatore", "Desenvolvedor", "개발", "开发者", "開發者", "Разработчик"],
    "settings.developer_site": ["Developer website", "開発者サイト", "Sitio del desarrollador", "Site du développeur", "Entwickler-Website", "Sito dello sviluppatore", "Site do desenvolvedor", "개발자 사이트", "开发者网站", "開發者網站", "Сайт разработчика"],
    "settings.display": ["Display", "表示", "Pantalla", "Affichage", "Anzeige", "Schermo", "Exibição", "디스플레이", "显示", "顯示", "Экран"],
    "settings.map_color": ["Map color", "マップカラー管理", "Color del mapa", "Couleur de la carte", "Kartenfarbe", "Colore mappa", "Cor do mapa", "지도 색상", "地图颜色", "地圖顏色", "Цвет карты"],
    "settings.map_color.teal": ["Teal", "ティール", "Verde azulado", "Sarcelle", "Petrol", "Verde acqua", "Verde-azulado", "청록", "青绿色", "藍綠色", "Бирюзовый"],
    "settings.map_color.amber": ["Amber", "アンバー", "Ámbar", "Ambre", "Bernstein", "Ambra", "Âmbar", "앰버", "琥珀色", "琥珀色", "Янтарный"],
    "settings.map_color.coral": ["Coral", "コーラル", "Coral", "Corail", "Koralle", "Corallo", "Coral", "코랄", "珊瑚色", "珊瑚色", "Коралловый"],
    "settings.map_color.ocean": ["Ocean", "オーシャン", "Océano", "Océan", "Ozean", "Oceano", "Oceano", "오션", "海洋蓝", "海洋藍", "Океан"],
    "settings.email": ["Email address", "メールアドレス", "Correo electrónico", "Adresse e-mail", "E-Mail-Adresse", "Indirizzo email", "Endereço de e-mail", "이메일 주소", "电子邮件地址", "電子郵件地址", "Адрес электронной почты"],
    "settings.faq": ["Frequently asked questions", "よくある質問", "Preguntas frecuentes", "Questions fréquentes", "Häufige Fragen", "Domande frequenti", "Perguntas frequentes", "자주 묻는 질문", "常见问题", "常見問題", "Частые вопросы"],
    "settings.geonames_description": bilingual("Offline city and alternate-name search for the additional regional maps uses GeoNames data under CC BY 4.0.", "追加した地域マップのオフライン都市・別名検索には、CC BY 4.0のGeoNamesデータを使用しています。"),
    "settings.guide": ["User guide", "利用ガイド", "Guía de uso", "Guide d’utilisation", "Benutzerhandbuch", "Guida all’uso", "Guia de uso", "이용 가이드", "使用指南", "使用指南", "Руководство"],
    "settings.information": ["Information", "情報", "Información", "Informations", "Informationen", "Informazioni", "Informações", "정보", "信息", "資訊", "Информация"],
    "settings.insee_description": bilingual("French department, region, and commune names and codes use Insee’s 2026 Code officiel géographique.", "フランスの地域圏・地域・コミューンの名称とコードには、InseeのCode officiel géographique 2026を使用しています。"),
    "settings.japan_address_description": bilingual("Japanese municipality search uses Geolonia’s address index, derived from Japanese government address data.", "日本の市区町村検索には、日本政府の住所データをもとにしたGeoloniaの住所インデックスを使用しています。"),
    "settings.language": ["Language", "言語設定", "Idioma", "Langue", "Sprache", "Lingua", "Idioma", "언어", "语言", "語言", "Язык"],
    "settings.licenses": ["Open source licenses", "オープンソースライセンス", "Licencias de código abierto", "Licences open source", "Open-Source-Lizenzen", "Licenze open source", "Licenças de código aberto", "오픈 소스 라이선스", "开源许可证", "開放原始碼授權", "Лицензии открытого ПО"],
    "settings.natural_earth": ["Natural Earth data", "Natural Earth データ", "Datos de Natural Earth", "Données Natural Earth", "Natural-Earth-Daten", "Dati Natural Earth", "Dados do Natural Earth", "Natural Earth 데이터", "Natural Earth 数据", "Natural Earth 資料", "Данные Natural Earth"],
    "settings.natural_earth_description": ["Colorvia uses public-domain Natural Earth map data.", "ColorviaはパブリックドメインのNatural Earth地図データを使用しています。", "Colorvia utiliza datos cartográficos de dominio público de Natural Earth.", "Colorvia utilise les données cartographiques du domaine public Natural Earth.", "Colorvia verwendet gemeinfreie Kartendaten von Natural Earth.", "Colorvia utilizza dati cartografici Natural Earth di pubblico dominio.", "O Colorvia usa dados de mapa em domínio público do Natural Earth.", "Colorvia는 퍼블릭 도메인 Natural Earth 지도 데이터를 사용합니다.", "Colorvia使用公共领域的Natural Earth地图数据。", "Colorvia 使用公有領域的 Natural Earth 地圖資料。", "Colorvia использует общедоступные картографические данные Natural Earth."],
    "settings.official_site": ["Official website", "公式サイト", "Sitio oficial", "Site officiel", "Offizielle Website", "Sito ufficiale", "Site oficial", "공식 사이트", "官方网站", "官方網站", "Официальный сайт"],
    "settings.personalization": ["Personalization", "カスタマイズ", "Personalización", "Personnalisation", "Personalisierung", "Personalizzazione", "Personalização", "개인 설정", "个性化", "個人化", "Персонализация"],
    "settings.privacy": ["Privacy policy", "プライバシーポリシー", "Política de privacidad", "Politique de confidentialité", "Datenschutzrichtlinie", "Informativa sulla privacy", "Política de privacidade", "개인정보 처리방침", "隐私政策", "隱私權政策", "Политика конфиденциальности"],
    "settings.reset_all": ["Delete all visit data", "すべての訪問データを削除", "Eliminar todos los datos de visitas", "Supprimer toutes les visites", "Alle Besuchsdaten löschen", "Elimina tutti i dati delle visite", "Excluir todos os dados de visita", "모든 방문 데이터 삭제", "删除所有访问数据", "刪除所有造訪資料", "Удалить все данные о посещениях"],
    "settings.reset_confirm": ["Delete your visit data?", "訪問データを削除しますか？", "¿Eliminar los datos de visitas?", "Supprimer vos visites ?", "Besuchsdaten löschen?", "Eliminare i dati delle visite?", "Excluir os dados de visita?", "방문 데이터를 삭제할까요?", "删除访问数据？", "刪除造訪資料？", "Удалить данные о посещениях?"],
    "settings.contact": ["Contact us", "お問合せ", "Contacto", "Nous contacter", "Kontakt", "Contatti", "Fale conosco", "문의하기", "联系我们", "聯絡我們", "Связаться с нами"],
    "settings.copyright": ["Copyright", "コピーライト", "Copyright", "Copyright", "Copyright", "Copyright", "Copyright", "저작권", "版权", "著作權", "Авторские права"],
    "settings.support": ["Support", "サポート", "Ayuda", "Assistance", "Support", "Supporto", "Suporte", "지원", "支持", "支援", "Поддержка"],
    "settings.terms": ["Terms of use", "利用規約", "Términos de uso", "Conditions d’utilisation", "Nutzungsbedingungen", "Termini di utilizzo", "Termos de uso", "이용 약관", "使用条款", "使用條款", "Условия использования"],
    "settings.theme": ["Theme", "テーマ管理", "Tema", "Thème", "Design", "Tema", "Tema", "테마", "主题", "主題", "Тема"],
    "settings.title": ["Settings", "設定", "Ajustes", "Réglages", "Einstellungen", "Impostazioni", "Ajustes", "설정", "设置", "設定", "Настройки"],
    "settings.updates": ["What’s new", "アップデート情報", "Novedades", "Nouveautés", "Neuigkeiten", "Novità", "Novidades", "업데이트 정보", "更新信息", "更新資訊", "Что нового"],
    "settings.version": ["Version information", "バージョン情報", "Información de versión", "Informations de version", "Versionsinformationen", "Informazioni sulla versione", "Informações da versão", "버전 정보", "版本信息", "版本資訊", "Информация о версии"],
    "settings.view_source": ["View data source", "データ提供元を見る", "Ver fuente de datos", "Voir la source des données", "Datenquelle anzeigen", "Visualizza origine dati", "Ver fonte dos dados", "데이터 출처 보기", "查看数据来源", "查看資料來源", "Открыть источник данных"],
    "stats.by_continent": ["By continent", "大陸別", "Por continente", "Par continent", "Nach Kontinent", "Per continente", "Por continente", "대륙별", "按大洲", "依洲別", "По континентам"],
    "stats.close": ["Collapse statistics", "統計を閉じる", "Contraer estadísticas", "Réduire les statistiques", "Statistik schließen", "Chiudi statistiche", "Recolher estatísticas", "통계 닫기", "收起统计", "收合統計", "Свернуть статистику"],
    "stats.no_countries": ["No countries visited yet", "訪れた国はまだありません", "Aún no hay países visitados", "Aucun pays visité", "Noch keine Länder besucht", "Nessun paese visitato", "Nenhum país visitado ainda", "아직 방문한 국가가 없어요", "尚无到访国家", "尚無造訪國家", "Пока нет посещённых стран"],
    "stats.open": ["Expand statistics", "統計を開く", "Ampliar estadísticas", "Développer les statistiques", "Statistik öffnen", "Apri statistiche", "Expandir estatísticas", "통계 열기", "展开统计", "展開統計", "Развернуть статистику"],
    "stats.swipe_up": ["Swipe up to see statistics", "上にスワイプして統計を表示", "Desliza hacia arriba para ver las estadísticas", "Balayez vers le haut pour voir les statistiques", "Nach oben wischen für Statistiken", "Scorri in alto per le statistiche", "Deslize para cima para ver as estatísticas", "위로 쓸어올려 통계 보기", "向上滑动查看统计", "向上滑動查看統計", "Проведите вверх, чтобы увидеть статистику"],
    "stats.title": ["Your world", "あなたの世界", "Tu mundo", "Votre monde", "Deine Welt", "Il tuo mondo", "Seu mundo", "나의 세계", "你的世界", "你的世界", "Ваш мир"],
    "stats.visited_countries": ["Visited countries", "訪れた国", "Países visitados", "Pays visités", "Besuchte Länder", "Paesi visitati", "Países visitados", "방문한 국가", "到访国家", "造訪國家", "Посещённые страны"],
    "stats.world_percentage": ["World explored", "世界の割合", "Mundo explorado", "Monde exploré", "Erkundete Welt", "Mondo esplorato", "Mundo explorado", "탐험한 세계", "探索世界比例", "探索世界比例", "Исследовано мира"],
    "subdivision.choose": bilingual("Choose regions", "地域を選ぶ"),
    "subdivision.map_accessibility": bilingual("Read-only regional map", "閲覧専用の地域マップ"),
    "subdivision.open_map": bilingual("Open regional map", "地域マップを開く"),
    "subdivision.parent_required": bilingual(
        "To use the regional map, mark this country as visited first.",
        "地域マップを利用するには、先にこの国を訪問済みにしてください。",
    ),
    "settings.import_parent_title": bilingual(
        "Regions have unvisited parent countries",
        "未訪問国の地域データがあります",
    ),
    "settings.import_repair_parents": bilingual(
        "Mark countries visited and import",
        "国を訪問済みに補正して読み込む",
    ),
    "settings.import_skip_regions": bilingual(
        "Skip those regions and import",
        "該当地域を除外して読み込む",
    ),
    "subdivision.progress": bilingual("Regional progress", "地域の進捗"),
    "subdivision.regions": bilingual("Regions", "地域"),
    "subdivision.remove_all": bilingual("Remove country and all regions", "国と地域をすべて外す"),
    "subdivision.search": bilingual("Region, city, or landmark", "地域名・都市名・観光地"),
    "subdivision_share.country_map": bilingual("Country map", "地域マップ"),
    "subdivision_share.map_only": bilingual("Map only", "地図のみ"),
    "subdivision_share.square": bilingual("Square poster", "正方形ポスター"),
    "subdivision_share.story": bilingual("Story poster", "ストーリーポスター"),
    "subdivision_share.title": bilingual("Share regional map", "地域マップを共有"),
    "privacy.analytics.body": ["The current version does not include advertising trackers or behavioral analytics.", "現在のバージョンには広告トラッカーや行動分析を実装していません。", "La versión actual no incluye rastreadores publicitarios ni análisis de comportamiento.", "La version actuelle n’inclut aucun traceur publicitaire ni analyse comportementale.", "Die aktuelle Version enthält keine Werbetracker oder Verhaltensanalyse.", "La versione attuale non include tracker pubblicitari o analisi comportamentali.", "A versão atual não inclui rastreadores de anúncios nem análise comportamental.", "현재 버전에는 광고 추적기나 행동 분석이 없습니다.", "当前版本不包含广告跟踪器或行为分析。", "目前版本不包含廣告追蹤器或行為分析。", "Текущая версия не содержит рекламных трекеров или поведенческой аналитики."],
    "privacy.analytics.title": ["Analytics", "分析について", "Analítica", "Analyse", "Analyse", "Analisi", "Análises", "분석", "分析", "分析", "Аналитика"],
    "privacy.collection.body": ["Colorvia does not require an account, location, photos, or contact information.", "Colorviaはアカウント、位置情報、写真、連絡先情報を要求しません。", "Colorvia no requiere cuenta, ubicación, fotos ni contactos.", "Colorvia ne demande ni compte, ni localisation, ni photos, ni contacts.", "Colorvia benötigt weder Konto, Standort, Fotos noch Kontakte.", "Colorvia non richiede account, posizione, foto o contatti.", "O Colorvia não exige conta, localização, fotos ou contatos.", "Colorvia는 계정, 위치, 사진, 연락처 정보를 요구하지 않습니다.", "Colorvia不需要账户、位置、照片或联系人信息。", "Colorvia 不需要帳號、位置、照片或聯絡資訊。", "Colorvia не требует аккаунт, геолокацию, фотографии или контакты."],
    "privacy.collection.title": ["Information we collect", "収集する情報", "Información que recopilamos", "Informations collectées", "Erfasste Informationen", "Informazioni raccolte", "Informações coletadas", "수집하는 정보", "收集的信息", "收集的資訊", "Собираемая информация"],
    "privacy.storage.body": ["Your visited-country selections are stored on your device. You can delete them from Data Management.", "訪問国の選択は端末内に保存され、データ管理から削除できます。", "Los países visitados se guardan en el dispositivo y se pueden eliminar en Gestión de datos.", "Vos pays visités sont stockés sur l’appareil et peuvent être supprimés dans Gestion des données.", "Besuchte Länder werden auf dem Gerät gespeichert und können in der Datenverwaltung gelöscht werden.", "I paesi visitati sono salvati sul dispositivo e possono essere eliminati da Gestione dati.", "Os países visitados são salvos no dispositivo e podem ser excluídos em Gerenciamento de dados.", "방문 국가 선택은 기기에 저장되며 데이터 관리에서 삭제할 수 있습니다.", "到访国家选择存储在设备上，可在数据管理中删除。", "造訪國家選擇會儲存在裝置上，可在資料管理中刪除。", "Выбранные страны хранятся на устройстве и удаляются в разделе управления данными."],
    "privacy.storage.title": ["Data storage", "データ保存", "Almacenamiento de datos", "Stockage des données", "Datenspeicherung", "Archiviazione dati", "Armazenamento de dados", "데이터 저장", "数据存储", "資料儲存", "Хранение данных"],
    "terms.disclaimer.body": ["Map boundaries and country classifications are provided for visualization and do not express a political position.", "地図の境界線と国・地域の分類は表示目的であり、政治的立場を示すものではありません。", "Los límites y clasificaciones se muestran con fines visuales y no expresan una postura política.", "Les frontières et classifications sont affichées à titre visuel et n’expriment aucune position politique.", "Grenzen und Klassifizierungen dienen der Darstellung und stellen keine politische Position dar.", "Confini e classificazioni sono visuali e non esprimono posizioni politiche.", "Fronteiras e classificações são apenas visuais e não expressam posição política.", "지도 경계와 국가 분류는 시각화를 위한 것이며 정치적 입장을 나타내지 않습니다.", "地图边界和国家分类仅用于可视化，不代表任何政治立场。", "地圖邊界和國家分類僅供視覺呈現，不代表任何政治立場。", "Границы и классификации показаны для визуализации и не выражают политическую позицию."],
    "terms.disclaimer.title": ["Map disclaimer", "地図に関する免責", "Aviso sobre el mapa", "Avertissement relatif à la carte", "Kartenhinweis", "Avviso sulla mappa", "Aviso sobre o mapa", "지도 면책", "地图免责声明", "地圖免責聲明", "Отказ от ответственности за карту"],
    "terms.service.body": ["Colorvia is provided as a simple tool for recording countries you have visited.", "Colorviaは訪れた国を記録するためのシンプルなツールとして提供されます。", "Colorvia se ofrece como una herramienta sencilla para registrar países visitados.", "Colorvia est fourni comme outil simple pour noter les pays visités.", "Colorvia ist ein einfaches Werkzeug zum Erfassen besuchter Länder.", "Colorvia è uno strumento semplice per registrare i paesi visitati.", "O Colorvia é uma ferramenta simples para registrar países visitados.", "Colorvia는 방문한 국가를 기록하는 간단한 도구입니다.", "Colorvia是一款记录到访国家的简单工具。", "Colorvia 是記錄造訪國家的簡單工具。", "Colorvia — простой инструмент для учёта посещённых стран."],
    "terms.service.title": ["Service", "サービスについて", "Servicio", "Service", "Dienst", "Servizio", "Serviço", "서비스", "服务", "服務", "Сервис"],
    "terms.use.body": ["Use the app lawfully and do not attempt to interfere with its operation or distribution.", "法令を守り、アプリの動作や配布を妨げる行為を行わないでください。", "Usa la app legalmente y no interfieras con su funcionamiento o distribución.", "Utilisez l’app légalement et ne perturbez pas son fonctionnement ou sa distribution.", "Nutze die App rechtmäßig und störe weder Betrieb noch Verteilung.", "Usa l’app legalmente e non interferire con funzionamento o distribuzione.", "Use o app legalmente e não interfira em seu funcionamento ou distribuição.", "법률을 준수하고 앱의 운영이나 배포를 방해하지 마세요.", "请合法使用本应用，不得干扰其运行或分发。", "請合法使用本 App，不得干擾其運作或散布。", "Используйте приложение законно и не мешайте его работе или распространению."],
    "terms.use.title": ["Acceptable use", "利用上のルール", "Uso aceptable", "Utilisation acceptable", "Zulässige Nutzung", "Uso consentito", "Uso aceitável", "이용 규칙", "使用规范", "使用規範", "Допустимое использование"],
    "updates.version.body": ["Initial preview with the interactive world map, country selection, statistics, themes, and multilingual support.", "インタラクティブな世界地図、国選択、統計、テーマ、多言語対応を含む初期プレビューです。", "Vista previa inicial con mapa interactivo, selección de países, estadísticas, temas e idiomas.", "Aperçu initial avec carte interactive, sélection des pays, statistiques, thèmes et langues.", "Erste Vorschau mit interaktiver Weltkarte, Länderauswahl, Statistik, Designs und Sprachen.", "Anteprima iniziale con mappa interattiva, selezione paesi, statistiche, temi e lingue.", "Prévia inicial com mapa interativo, seleção de países, estatísticas, temas e idiomas.", "대화형 세계 지도, 국가 선택, 통계, 테마와 다국어를 포함한 초기 미리보기입니다.", "初始预览包含交互式世界地图、国家选择、统计、主题和多语言支持。", "初始預覽包含互動式世界地圖、國家選擇、統計、主題和多語言支援。", "Первая версия с интерактивной картой, выбором стран, статистикой, темами и языками."],
    "updates.version.title": ["Version 1.0.0", "バージョン 1.0.0", "Versión 1.0.0", "Version 1.0.0", "Version 1.0.0", "Versione 1.0.0", "Versão 1.0.0", "버전 1.0.0", "版本 1.0.0", "版本 1.0.0", "Версия 1.0.0"],
    "unit.countries": ["countries", "か国", "países", "pays", "Länder", "paesi", "países", "개국", "个国家", "個國家", "стран"],
    "unit.country_one": ["country", "か国", "país", "pays", "Land", "paese", "país", "개국", "个国家", "個國家", "страна"],
    "unit.prefectures": bilingual("prefectures", "都道府県"),
    "unit.regions": bilingual("regions", "地域"),
}


def main():
    strings = {}
    for key, values in STRINGS.items():
        if len(values) != len(LANGUAGES):
            raise ValueError(f"{key}: expected {len(LANGUAGES)} translations, got {len(values)}")
        strings[key] = {
            "extractionState": "manual",
            "localizations": {
                language: {"stringUnit": {"state": "translated", "value": value}}
                for language, value in zip(LANGUAGES, values)
            },
        }

    output = Path("Colorvia/Resources/Localizable.xcstrings")
    output.write_text(
        json.dumps(
            {"sourceLanguage": "en", "strings": strings, "version": "1.0"},
            ensure_ascii=False,
            indent=2,
        )
        + "\n"
    )
    print(f"Wrote {len(strings)} keys in {len(LANGUAGES)} languages to {output}")


if __name__ == "__main__":
    main()
